<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:07:31 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Báo cáo danh tiếng';
$l['nav_profile'] = 'Hồ sơ của {1}';
$l['reputation_disabled'] = 'Bạn không thể sử dụng hệ thống danh tiếng, nó đã bị vô hiệu hóa bởi Administrator.';
$l['reputation'] = 'Danh tiếng';
$l['error'] = 'Lỗi';
$l['add_no_uid'] = 'Bạn chưa chỉ định một người dùng.';
$l['add_no_permission'] = 'Bạn không có quyền xếp hạng danh tiếng cho người dùng.';
$l['add_disabled'] = 'Bạn không thể thêm danh tiếng cho người dùng của nhóm này.';
$l['add_yours'] = 'Bạn không có thể thêm danh tiếng cho chính bạn.';
$l['add_invalidpower'] = 'Bạn đã chọn một xếp hạng không hợp lệ từ danh sách.';
$l['add_maxperday'] = 'Bạn đã cho đủ điểm danh tiếng của ngày hôm nay.';
$l['add_maxperuser'] = 'Bạn đã cho thành viên này đủ điểm danh tiếng của ngày hôm nay.';
$l['add_maxperthread'] = 'Bạn đã cho thành viên này đủ điểm đánh giá (trong một bài viết) của ngày hôm nay.';
$l['add_no_comment'] = 'Bạn phải nhập vào lời nhận xét ít nhất {1} từ để cho điểm danh tiếng cho thành viên này.';
$l['add_toolong'] = 'Bạn phải nhập vào lý do không quá {1} từ.';
$l['add_negative_disabled'] = 'Người quản trị đã vô hiệu hóa danh tiếng tiêu cực.';
$l['add_neutral_disabled'] = 'Quản trị viên đã vô hiệu hóa danh tiếng trung lập.';
$l['add_positive_disabled'] = 'Các quản trị viên đã vô hiệu hóa danh tiếng tích cực.';
$l['add_all_rep_disabled'] = 'Các quản trị viên đã vô hiệu hóa tất cả các loại danh tiếng. Bạn không thể xếp hạng người sử dụng này.';
$l['reputation_report'] = 'Báo cáo điểm danh tiếng cho {1}';
$l['reputation_members'] = 'Danh tiếng từ thành viên:';
$l['reputation_posts'] = 'Danh tiếng từ bài viết:';
$l['summary'] = 'Tóm tắt';
$l['total_reputation'] = 'Số danh tiếng hiện có';
$l['post_reputation'] = 'Đăng Danh tiếng';
$l['positive_count'] = 'Tích cực';
$l['neutral_count'] = 'Bình thường';
$l['negative_count'] = 'Tiêu cực';
$l['last_week'] = 'Tuần trước';
$l['last_month'] = 'Tháng trước';
$l['last_6months'] = '6 tháng trước';
$l['all_time'] = 'Tất cả thời gian';
$l['comments'] = 'Lời bình luận';
$l['close_window'] = 'Đóng cửa sổ';
$l['add_reputation_vote'] = 'Cho điểm danh tiếng cho {1}';
$l['add_reputation_to_post'] = 'Điểm danh tiếng này là cho bài viết của {1}.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>Điểm danh tiếng tiêu cực hiện đang tắt</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em>Danh tiếng tích cực hiện đang bị vô hiệu hóa</em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em>Danh tiếng trung lập hiện đang bị vô hiệu hóa</em></span>';
$l['no_comment_needed'] = 'Bạn cho điểm danh tiếng vì bài post của thành viên này, có liên kết trong hồ sơ của họ. Lời bình luận không là cần thiết, nhưng nếu bạn muốn, xin hãy nhập vào bên dưới.<br />';
$l['no_comment'] = '[Không có bình luận]';
$l['vote_added'] = 'Đã thêm đánh giá';
$l['vote_updated'] = 'Đã cập nhật đánh giá';
$l['vote_deleted'] = 'Đã xóa đánh giá';
$l['vote_added_message'] = 'Đánh giá của bạn đã được thêm vào cho thành viên này.';
$l['vote_updated_message'] = 'Đánh giá của bạn đã được cập nhật cho thành viên này.';
$l['vote_deleted_message'] = 'Đánh giá của bạn đã được xóa từ thành viên này.';
$l['update_reputation_vote'] = 'Cập nhật đánh giá của bạn cho {1}';
$l['positive'] = 'Tích cực';
$l['negative'] = 'Tiêu cực';
$l['neutral'] = 'Bình thường';
$l['user_comments'] = 'Bình luận của bạn cho {1}:';
$l['add_vote'] = 'Đánh giá';
$l['update_vote'] = 'Cập nhật đánh giá';
$l['delete_vote'] = 'Xóa đánh giá';
$l['report_vote'] = 'Báo cáo';
$l['power_positive'] = 'Tích cực ({1})';
$l['power_neutral'] = 'Neutral';
$l['power_negative'] = 'Tiêu cực ({1})';
$l['show_all'] = 'Hiện: Tất cả bình chọn';
$l['show_positive'] = 'Hiện: Đánh giá tích cực';
$l['show_neutral'] = 'Hiện: Đánh giá trung lập';
$l['show_negative'] = 'Hiện: Đánh giá tiêu cực';
$l['sort_updated'] = 'Sắp xếp theo: Lần cập nhật cuối';
$l['sort_username'] = 'Sắp xếp theo: Tên đăng nhập';
$l['last_updated'] = 'Cập nhật lần cuối {1}';
$l['postrep_given'] = 'Đánh giá trao cho <a href="{1}">{2}\'s bài viết</a> {3}<br />';
$l['postrep_given_nolink'] = 'Rating given for {1}\'s post<br />';
$l['postrep_given_thread'] = 'trong <a href="{1}">{2}</a>';
$l['no_reputation_votes'] = 'Thành viên này hiện không có bất kỳ điểm danh tiếng nào với các tiêu chuẩn quy định dưới đây.';
$l['delete_reputation_confirm'] = 'Bạn có chắc là bạn muốn xóa điểm đánh giá danh tiếng này?';
$l['delete_reputation_log'] = 'Gỡ bỏ Danh tiếng bởi {1} (UID: {2})';
$l['reputations_disabled_group'] = 'Các hệ thống danh tiếng bị vô hiệu hóa cho người dùng của nhóm này.';
$l['rate_user'] = 'Đánh giá thành viên';
