<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:08:19 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Tìm kiếm';
$l['nav_results'] = 'Kết quả';
$l['pages_last'] = 'trước';
$l['search'] = 'Tìm kiếm';
$l['search_keyword'] = 'Tìm kiếm theo từ khóa';
$l['search_username'] = 'Tìm kiếm theo Username';
$l['search_entire_post'] = 'Tìm kiếm toàn bộ bài viết';
$l['search_titles_only'] = 'Chỉ tìm tiêu đề';
$l['match_username'] = 'Phù hợp với tên thành viên';
$l['search_forums'] = 'Tìm trong diễn đàn';
$l['search_all_forums'] = 'Tìm trong tất cả các diễn đàn mở';
$l['search_options'] = 'Tùy chọn tìm kiếm';
$l['threads_at_least'] = 'Tìm chủ đề ít với nhất là';
$l['threads_at_most'] = 'Tìm chủ đề với với nhiều nhất là';
$l['find_anydate'] = 'Tìm các bài viết theo ngày bất kỳ';
$l['find_yesterday'] = 'Tìm các bài viết từ hôm qua';
$l['find_lastweek'] = 'Tìm bài viết từ tuần trước';
$l['find_2weeks'] = 'Tìm các bài viết từ 2 tuần trước';
$l['find_month'] = 'Tìm bài viết từ tháng trước';
$l['find_3months'] = 'Tìm các bài viết từ 3 tháng trước';
$l['find_6months'] = 'Tìm các bài viết từ 6 tháng trước';
$l['find_year'] = 'Tìm các bài viết từ 1 năm trước';
$l['and_newer'] = 'Và mới hơn';
$l['and_older'] = 'Và cũ hơn';
$l['sorting_options'] = 'Thiết lập sắp xếp';
$l['sort_lastpost'] = 'Sắp xếp theo ngày';
$l['sort_author'] = 'Sắp xếp theo tên tác giả';
$l['sort_forum'] = 'Sắp xếp theo chuyên mục';
$l['sort_in'] = 'Sắp xếp';
$l['sort_asc'] = 'Tăng dần';
$l['sort_desc'] = 'Giảm dần';
$l['sort_order'] = 'Thứ tự';
$l['asc'] = 'Tăng dần';
$l['desc'] = 'Giảm dần';
$l['display_options'] = 'Thiết lập hiển thị';
$l['show_results_as'] = 'Hiển thị kết quả theo';
$l['show_results_threads'] = 'Chủ đề';
$l['show_results_posts'] = 'Bài viết';
$l['search_results'] = 'Kết quả tìm kiếm';
$l['post'] = 'Bài viết';
$l['author'] = 'Tác giả';
$l['forum'] = 'Diễn đàn';
$l['replies'] = 'Trả lời';
$l['views'] = 'Xem';
$l['posted'] = 'Được đăng';
$l['thread'] = 'Chủ đề';
$l['lastpost'] = 'Bài viết cuối';
$l['post_thread'] = 'Chủ đề:';
$l['post_subject'] = 'Bài viết:';
$l['replies2'] = 'Trả lời';
$l['selectall'] = 'Chọn tất cả các kết quả bổ sung?';
$l['any_prefix'] = 'Find threads with any prefix';
$l['no_prefix'] = 'Không có prefix';
$l['inline_thread_moderation'] = 'Inline Thread Moderation:';
$l['close_threads'] = 'Đóng chủ đề';
$l['open_threads'] = 'Mở chủ đề';
$l['stick_threads'] = 'Đính chủ đề';
$l['unstick_threads'] = 'Bỏ đính chủ đề';
$l['soft_delete_threads'] = 'Soft Delete Threads';
$l['restore_threads'] = 'Restore Threads';
$l['delete_threads'] = 'Xóa chủ đề';
$l['move_threads'] = 'Di chuyển chủ đề';
$l['approve_threads'] = 'Phê duyệt';
$l['unapprove_threads'] = 'Bỏ phê duyệt';
$l['inline_soft_delete_posts'] = 'Xóa mềm';
$l['inline_restore_posts'] = 'Khôi phục bài viết';
$l['inline_delete_posts'] = 'Xóa vĩnh viễn';
$l['inline_merge_posts'] = 'Trộn bài viết';
$l['inline_split_posts'] = 'Tách bài viết';
$l['inline_move_posts'] = 'Move Posts';
$l['inline_approve_posts'] = 'Phê duyệt';
$l['inline_unapprove_posts'] = 'Bỏ phê duyệt';
$l['inline_post_moderation'] = 'Inline Post Moderation:';
$l['inline_go'] = 'Go';
$l['clear'] = 'Xóa';
$l['icon_dot'] = 'Có chứa bài viết của bạn.';
$l['icon_no_new'] = 'Không có bài mới.';
$l['icon_new'] = 'Bài mới.';
$l['icon_hot'] = ' Chủ đề Hot.';
$l['icon_lock'] = ' Chủ đề đã khóa.';
$l['attachment_count'] = 'Chủ đề này có chứa 1 tập tin đính kèm.';
$l['attachment_count_multiple'] = 'Chủ đề này có chứa {1} tập tin đính kèm.';
$l['goto_first_unread'] = 'Tới bài chưa đọc đầu tiên';
$l['page_selected'] = 'Có tất cả <strong>{1}</strong> kết quả trên trang này được đã lựa chọn.';
$l['all_selected'] = 'Có tất cả <strong>{1}</strong> kết quả trong tìm kiếm này đã được lựa chọn.';
$l['select_all'] = 'Có tất cả <strong>{1}</strong> kết quả trong tìm kiếm này.';
$l['clear_selection'] = 'Xóa lựa chọn.';
$l['results'] = 'Kết quả';
$l['mod_options'] = 'Công cụ quản lý';
$l['display_all'] = 'Hiển thị tất cả';
$l['display_only_approved'] = 'Chỉ hiển thị đã được phê duyệt';
$l['display_only_unapproved'] = 'Chỉ hiển thị chưa được phê duyệt';
$l['display_only_softdeleted'] = 'Chỉ hiển thị xóa mềm';
$l['redirect_searchresults'] = 'Cảm ơn bạn, tìm kiếm của bạn đã được gửi đi và bây giờ bạn sẽ được đưa tới danh sách kết quả.';
$l['error_minsearchlength'] = 'Thuật ngữ tìm kiếm của bạn ngắn hơn độ dài tối thiểu. Chiều dài thuật ngữ tìm kiếm tối thiểu là {1} ký tự.<br /><br />Nếu bạn đang cố gắng để tìm kiếm một cụm từ, hãy đặt nó trong dấu ngoặc kép. Ví dụ "Security - Diễn đàn bảo mật website".';
$l['error_nosearchresults'] = 'Xin lỗi, nhưng chúng tôi không tìm thấy kết quả nào phù hợp với yêu cầu của bạn. Vui lòng thử lại với một từ khóa khác.';
$l['error_no_search_support'] = 'Cơ sở dữ liệu này không hỗ trợ tìm kiếm.';
$l['error_nosearchterms'] = 'Bạn chưa nhập điều kiện tìm kiếm. Ở mức tối thiểu, bạn phải nhập một số thuật ngữ tìm kiếm hoặc tên thành viên để tìm kiếm.';
$l['error_searchflooding_1'] = 'Xin lỗi, nhưng bạn chỉ có thể thực hiện mộĩ một tìm kiếm cách nhau {1} giây. Hãy chờ thêm 1 giây trước khi cố gắng tìm kiếm lại.';
$l['error_searchflooding'] = 'Xin lỗi, nhưng bạn chỉ có thể thực hiện mộĩ một tìm kiếm cách nhau{1} giây. Hãy chờ thêm {2} giây trước khi cố gắng tìm kiếm lại.';
$l['error_invalidsearch'] = 'Bạn đang thực hiện một tìm kiếm không hợp lệ. Xin vui lòng thử lại';
$l['sort_views'] = 'Sắp xếp kết quả theo số lượt xem';
$l['sort_replies'] = 'Sắp xếp kết quả theo số lượng trả lời';
$l['icon_close'] = 'Chủ đề đã đóng.';
