<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:09:06 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Đội ngũ điều hành';
$l['forum_team'] = 'Đội ngũ điều hành';
$l['moderators'] = 'Moderators';
$l['username'] = 'Username';
$l['lastvisit'] = 'Lần đăng nhập cuối';
$l['email'] = 'Email';
$l['pm'] = 'PM';
$l['mod_forums'] = 'Diễn đàn';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['away'] = 'Away';
$l['group_leaders'] = 'Quản lý';
$l['group_members'] = 'Thành viên';
$l['no_members'] = 'Không có thành viên nào trong nhóm';
$l['error_noteamstoshow'] = 'Không có đội ngũ điều hành để hiển thị.';
$l['mod_groups'] = 'Nhóm';
$l['showteam_disabled'] = 'Chức năng liệt kê nhóm diễn đàn đã bị Quản trị viên vô hiệu hóa.';
