<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:40:46 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'Bạn chưa nhập tên người dùng. Vui lòng nhập vào tên người dùng.';
$l['userdata_banned_username'] = 'Tên người dùng mà bạn đã nhập không được đăng ký. Vui lòng nhập một tên người dùng khác.';
$l['userdata_bad_characters_username'] = 'Tên người dùng bạn nhập chứa ký tự xấu. Vui lòng nhập một tên người dùng khác.';
$l['userdata_invalid_username_length'] = 'Tên người dùng bạn nhập vào có chiều dài không hợp lệ. Vui lòng nhập tên từ {1} đến {2} ký tự.';
$l['userdata_invalid_usertitle_length'] = 'Các danh hiệu mà bạn nhập vào có chiều dài không hợp lệ. Vui lòng nhập danh hiệu không quá {1} ký tự.';
$l['userdata_username_exists'] = 'Tên người dùng mà bạn đã nhập đã tồn tại. Vui lòng nhập một tên người dùng khác.';
$l['userdata_invalid_password_length'] = 'Mật khẩu bạn đã nhập có chiều dài không hợp lệ. Vui lòng nhập mật khẩu từ {1} đến {2} ký tự.';
$l['userdata_no_complex_characters'] = 'Mật khẩu bạn nhập vào không đủ phức tạp. Vui lòng nhập mật khẩu có ít nhất là {1} ký tự, và chứa một chữ hoa, chữ thường và một số.';
$l['userdata_passwords_dont_match'] = 'Mật khẩu xác nhận không chính xác. Vui lòng xác nhận mật khẩu của bạn một cách chính xác.';
$l['userdata_bad_password_security'] = 'Mật khẩu bạn nhập vào giống tên người dùng hoặc địa chỉ email. Vui lòng nhập một mật khẩu đủ mạnh.';
$l['userdata_missing_email'] = 'Bạn chưa nhập địa chỉ email. Vui lòng nhập email.';
$l['userdata_invalid_email_format'] = 'Địa chỉ email bạn đã nhập không hợp lệ. Xin vui lòng nhập một địa chỉ email hợp lệ.';
$l['userdata_emails_dont_match'] = 'Địa chỉ email xác nhận không chính xác. Vui lòng xác nhận địa chỉ email của bạn một cách chính xác.';
$l['userdata_banned_email'] = 'Các địa chỉ email bạn đã nhập không được phép sử dụng. Xin vui lòng nhập một địa chỉ email khác.';
$l['userdata_email_already_in_use'] = 'Bạn đã nhập một địa chỉ email đã được sử dụng bởi các thành viên khác. Xin vui lòng nhập một địa chỉ email khác.';
$l['userdata_dob_required'] = 'Bạn đã không chọn ngày sinh của bạn. Vui lòng chọn ngày sinh của bạn để tiếp tục - bạn có thể ẩn ngày sinh và tuổi của bạn.';
$l['userdata_invalid_website'] = 'Địa chỉ trang web mà bạn đã nhập không hợp lệ. Xin vui lòng nhập một địa chỉ trang web hợp lệ, hoặc bỏ trống.';
$l['userdata_invalid_icq_number'] = 'Số ICQ bạn đã nhập không hợp lệ. Xin vui lòng nhập một số ICQ hợp lệ, hoặc bỏ trống.';
$l['userdata_invalid_birthday'] = 'Ngày sinh bạn đã nhập không hợp lệ. Vui lòng nhập một ngày sinh hợp lệ.';
$l['userdata_invalid_birthday_coppa'] = 'Để xác minh tuổi của bạn, xin vui lòng nhập năm bạn được sinh ra. Bạn có thể ẩn tuổi và ngày sinh của bạn trong tùy chọn cá nhân của bạn.';
$l['userdata_invalid_birthday_coppa2'] = 'Bạn phải lớn hơn 13 tuổi để trở thành một thành viên của diễn đàn. Hãy liên hệ với quản trị viên.';
$l['userdata_invalid_birthday_privacy'] = 'Vui lòng chọn một tùy chọn bảo mật ngày sinh hợp lệ.';
$l['userdata_invalid_referrer'] = 'Người giới thiệu từ bạn nhập không tồn tại. Vui lòng nhập một người giới thiệu hợp lệ, hoặc bỏ trống.';
$l['userdata_invalid_language'] = 'Ngôn ngữ bạn chọn không tồn tại. Hãy lựa chọn một ngôn ngữ hiện có.';
$l['userdata_invalid_style'] = 'Các phong cách bạn chọn không hợp lệ. Vui lòng chọn một phong cách hợp lệ.';
$l['userdata_missing_returndate'] = 'Ngày trở về của bạn không chính xác. Hãy chắc chắn rằng bạn đã điền ngày, tháng, và năm.';
$l['userdata_missing_required_profile_field'] = 'Bạn đã không nhập một lựa chọn cho các "{1}" lĩnh vực. Vui lòng điền vào hoặc chọn một giá trị cho trường này.';
$l['userdata_bad_profile_field_value'] = 'Bạn đã không nhập một giá trị hợp lệ cho lĩnh vực "{1}". Vui lòng nhập một giá trị hợp lệ trước khi tiếp tục.';
$l['userdata_bad_profile_field_values'] = 'Bạn đã không chọn một lựa chọn hợp lệ cho lĩnh vực "{1}". Hãy lựa chọn một giá trị từ các lựa chọn được trình bày.';
$l['userdata_max_limit_reached'] = 'Bạn đã nhập sai số các ký tự cho lĩnh vực "{1}". Vui lòng điền vào lĩnh vực này không quá {2} ký tự.';
$l['userdata_invalid_checkfield'] = 'Nó đã được phát hiện ra rằng hình thức này đã được gửi bởi một bot spam. Nếu đây là lỗi, vui lòng liên hệ với quản trị viên.';
$l['userdata_invalid_postnum'] = 'Số lượng bài viết mà bạn đã nhập không hợp lệ. Xin vui lòng nhập một số lượng bài viết hợp lệ, hoặc bỏ trống.';
$l['userdata_invalid_threadnum'] = 'Số lượng chủ đề bạn đã nhập không hợp lệ. Xin vui lòng nhập một số lượng chủ đề hợp lệ, hoặc bỏ trống.';
$l['userdata_away_too_long'] = 'Lý do vắng mặt bạn chỉ định quá dài. Tối đa 200 ký tự được phép cho trường này. Vui lòng xóa {1} ký tự khỏi trường này.';
$l['userdata_too_many_sig_images'] = 'Chúng tôi xin lỗi, nhưng chúng tôi không thể cập nhật chữ ký của bạn vì nó chứa quá nhiều hình ảnh. Vui lòng xóa một số hình ảnh từ chữ ký của bạn để tiếp tục.';
$l['userdata_too_many_sig_images2'] = '<strong> Lưu ý: </ strong> Lượng hình ảnh tối đa cho chữ ký là {1}.';
$l['userdata_sig_too_long'] = 'Bạn không thể cập nhật chữ ký của mình vì nó quá dài. Độ dài tối đa cho chữ ký là {1} ký tự.';
$l['userdata_sig_remove_chars_plural'] = 'Vui lòng xóa {1} ký tự và thử lại.';
$l['userdata_sig_remove_chars_singular'] = 'Vui lòng xóa 1 ký tự và thử lại.';
