<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:33:52 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = 'Tiêu đề quá dài. Vui lòng nhập một tiêu đề ngắn hơn';
$l['pmdata_code_no_subject'] = '[Không có tiêu đề]';
$l['pmdata_missing_subject'] = 'Bạn chưa nhập tiêu đề. Vui lòng nhập tiêu đề.';
$l['pmdata_missing_message'] = 'Bạn chưa nhập tin nhắn. Vui lòng nhập một tin nhắn.';
$l['pmdata_invalid_recipients'] = 'Người nhận không hợp lệ. Vui lòng kiểm tra lại tên người nhận này: {1}';
$l['pmdata_no_recipients'] = 'Bạn chưa nhập tên người nhận. Bạn phải nhập ít nhất một người nhận để có thể gửi tin nhắn.';
$l['pmdata_too_many_recipients'] = 'Bạn chỉ được phép gửi tin nhắn đến {1} tại một thời điểm nhất định.';
$l['pmdata_recipient_is_ignoring'] = 'Bạn không thể gửi tin nhắn tới {1} bở vị bạn đang nằm trong danh sách bỏ qua của họ.';
$l['pmdata_recipient_has_buddy_only'] = 'Bạn không thể gửi tin nhắn tới {1} bởi vì bạn không nằm trong danh sách bạn bè của họ.';
$l['pmdata_recipient_pms_disabled'] = '{1} đã vô hiệu hóa chức năng nhận tin nhắn .Bạn không thể gởi tin nhắn cho thành viên này.';
$l['pmdata_recipient_reached_quota'] = '{1} đã đạt đến giới hạn của số tin nhắn được phép nhận nên bạn không thể gửi tin nhắn cho họ.';
$l['pmdata_pm_flooding'] = 'Bạn đang gửi tin nhắn quá nhanh, chúng tôi cho rằng bạn không đủ thời gian để suy nghĩ kỹ về nội dung tin nhắn. Vui lòng gửi lại sau {1} giây.';
$l['pmdata_pm_flooding_one_second'] = 'Bạn đang gửi tin nhắn quá nhanh, chúng tôi cho rằng không cần thiết phải vội vàng như vậy, hãy đợi thêm 1 giây nữa trước khi tiếp tục.';
$l['pmdata_message_too_long'] = 'Tin nhắn quá dài. Vui lòng nhập một tin nhắn ngắn hơn {1} ký tự (hiện tại {2}).';
