<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:41:44 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Tạo chủ đề';
$l['moderated_by'] = 'Quản lý bởi:';
$l['nothreads'] = 'Xin lỗi nhưng hiện tại chưa có chủ đề nào trong diễn đàn này.';
$l['nopermission'] = 'Xin lỗi, nhưng bạn không có quyền để xem các chủ đề trong diễn đàn này.';
$l['search_forum'] = 'Tìm trong chuyên mục này:';
$l['thread'] = 'Chủ đề';
$l['author'] = 'Tác giả';
$l['replies'] = 'Trả lời';
$l['views'] = 'Lượt xem';
$l['lastpost'] = 'Bài cuối';
$l['rating'] = 'Đánh giá';
$l['prefix'] = 'Prefix:';
$l['prefix_all'] = 'Prefix: Bất kỳ/Không Prefix';
$l['prefix_any'] = 'Prefix: Prefix bất kỳ';
$l['prefix_none'] = 'Prefix: Không Prefix';
$l['markforum_read'] = 'Đánh dấu chuyên mục đã xem';
$l['subscribe_forum'] = 'Đặt theo dõi chuyên mục';
$l['unsubscribe_forum'] = 'Bỏ theo dõi chuyên mục';
$l['clear_stored_password'] = 'Xoá mật khẩu lưu trữ';
$l['sort_by_subject'] = 'Phân loại theo: Tiêu đề';
$l['sort_by_lastpost'] = 'Phân loại theo: Bài mới';
$l['sort_by_starter'] = 'Phân loại theo: Tác giả';
$l['sort_by_started'] = 'Sắp xếp: Thời gian';
$l['sort_by_rating'] = 'Phân loại theo: Đánh giá';
$l['sort_by_replies'] = 'Phân loại theo: Trả lời';
$l['sort_by_views'] = 'Phân loại theo: Lượt xem';
$l['sort_order_asc'] = 'Thứ tự: Tăng dần';
$l['sort_order_desc'] = 'Thứ tự: Giảm dần';
$l['datelimit_1day'] = 'Thời gian: Hôm nay';
$l['datelimit_5days'] = 'Thời gian: 5 ngày trước';
$l['datelimit_10days'] = 'Thời gian: 10 ngày trước';
$l['datelimit_20days'] = 'Thời gian: 20 ngày trước';
$l['datelimit_50days'] = 'Thời gian: 50 ngày trước';
$l['datelimit_75days'] = 'Thời gian: 75 ngày trước';
$l['datelimit_100days'] = 'Thời gian: 100 ngày trước';
$l['datelimit_lastyear'] = 'Thời gian: Năm ngoái';
$l['datelimit_beginning'] = 'Thời gian: Bắt đầu';
$l['new_thread'] = 'Bài viết mới';
$l['new_hot_thread'] = 'Chủ đề nóng (Mới)';
$l['posts_by_you'] = 'Có bài của bạn';
$l['no_new_thread'] = 'Không có bài mới';
$l['hot_thread'] = 'Chủ đề nóng (Không có bài mới)';
$l['locked_thread'] = 'Chủ đề đã đóng';
$l['goto_first_unread'] = 'Chuyển đến bài viết chưa xem đầu tiên';
$l['pages'] = 'Trang:';
$l['pages_last'] = 'cuối';
$l['users_browsing_forum'] = 'Đang xem chuyên mục:';
$l['users_browsing_forum_guests'] = '{1} Khách(s)';
$l['users_browsing_forum_invis'] = '{1}  ẩn danh(s)';
$l['delayed_moderation'] = 'Chưa kiểm duyệt';
$l['inline_thread_moderation'] = 'Quản lý chủ đề:';
$l['close_threads'] = 'Đóng chủ đề';
$l['open_threads'] = 'Mở chủ đề';
$l['stick_threads'] = 'Ưu tiên';
$l['unstick_threads'] = 'Huỷ ưu tiên';
$l['soft_delete_threads'] = 'Xóa tạm chủ đề';
$l['restore_threads'] = 'Khôi phục chủ đề';
$l['delete_threads'] = 'Xóa chủ đề';
$l['move_threads'] = 'Di chuyển chủ đề';
$l['approve_threads'] = 'Duyệt chủ đề';
$l['unapprove_threads'] = 'Không duyệt chủ đề';
$l['inline_go'] = 'Thực hiện';
$l['clear'] = 'Xóa';
$l['sub_forums_in'] = 'Diễn đàn \'{1}\'';
$l['forum_rules'] = '{1} - Quy định';
$l['subforums'] = '<strong>Chuyên mục con:</strong>';
$l['asc'] = 'Tăng đần';
$l['desc'] = 'Giảm dần';
$l['forum_announcements'] = 'Thông báo diễn đàn';
$l['sticky_threads'] = 'Chủ đề quan trọng';
$l['normal_threads'] = 'Chủ đề bình thường';
$l['icon_dot'] = 'Có bài của bạn.';
$l['icon_no_new'] = 'Không có bài mới.';
$l['icon_new'] = 'Có bài mới.';
$l['icon_hot'] = ' Chủ đề nóng.';
$l['icon_lock'] = ' Chủ đề đã bị khoá.';
$l['attachment_count'] = 'Chủ đề này có 1 tập tin đính kèm.';
$l['attachment_count_multiple'] = 'Chủ đề này có {1} tập tin đính kèm.';
$l['rss_discovery_forum'] = 'Chủ đề cuối cùng trong {1}';
$l['forum_unapproved_posts_count'] = 'Hiện tại đang có {1} bài viết chưa được chấp nhận trong diễn đàn này.';
$l['forum_unapproved_post_count'] = 'Hiện tại đang có 1 bài viết chưa được chấp nhận trong diễn đàn này.';
$l['forum_unapproved_threads_count'] = 'Hiện tại đang có {1} chủ đề chưa được chấp nhận trong diễn đàn này.';
$l['forum_unapproved_thread_count'] = 'Hiện tại đang có 1 chủ đề chưa được chấp nhận trong diễn đàn này.';
$l['thread_unapproved_posts_count'] = 'Hiện tại đang có {1} bài viết chưa được chấp nhận trong chủ đề này.';
$l['thread_unapproved_post_count'] = 'Hiện tại đang có 1 bài viết chưa được chấp nhận trong chủ đề này.';
$l['page_selected'] = 'Tất cả <strong>{1}</strong> chủ đề trên trang này đã được chọn.';
$l['all_selected'] = 'Tất cả <strong>{1}</strong> chủ đề trong diễn đàn này đã được chọn.';
$l['select_all'] = 'Chọn tất cả <strong>{1}</strong> chủ đề trong diễn đàn này.';
$l['clear_selection'] = 'Xóa lựa chọn.';
$l['error_containsnoforums'] = 'Diễn đàn bạn đang xem hiện tại không có mục con nào.';
$l['inline_edit_description'] = '(Bấm và giữ để chỉnh sửa)';
$l['closed_thread'] = 'Chủ đề đã đóng';
$l['icon_close'] = 'Chủ đề đã Đóng.';
$l['deleted_thread'] = 'Chủ đề đã Xóa';
