<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:53:24 +0000
// --------------------------------------------------------------------------------

$l['d1_name'] = 'Đăng ký thành viên';
$l['d1_desc'] = 'Quyền lợi và nghĩa vụ của thành viên.';
$l['d1_document'] = 'Một số khu vực của diễn đàn yêu cầu bạn phải đăng nhập để xem. Việc đăng ký thành viên là hoàn toàn miễn phí và chỉ tốn vài phút để hoàn thành.
<br /><br />Chúng tôi khuyến khích bạn nên đăng ký thành viên, là thành viên bạn có thể viết bài, gởi tin nhắn, tìm thấy những gì mình thích.
<br /><br />Một vài nét đặc trưng của thành viên là chức năng theo dõi chủ đề, thay đổi giao diện, viết ghi chú cá nhân và gởi email cho thành viên trong diễn đàn.';
$l['d2_name'] = 'Cập nhật thông tin cá nhân';
$l['d2_desc'] = 'Thay đổi thông tin cá nhân của bạn.';
$l['d2_document'] = 'Bạn có thể cập nhật thông tin của mình như gởi tin nhắn, thay đổi mật khẩu, thay đổi địa chỉ email. Bạn có thể thay đổi bất kỳ thông tin nào trong bảng điều khiển cá nhân. Để vào bảng điều khiển cá nhân bạn có thể click vào  "User CP". Từ đó, ví dụ bạn chọn  "Sửa thông tin" và thay đổi hoặc cập nhật bất kỳ thông tin nào, sau đó bấm vào nút ở phía dưới của trang để lưu những thay đổi.';
$l['d3_name'] = 'Sử dụng Cookies trên MyBB';
$l['d3_desc'] = 'MyBB sử dụng cookies để lưu thông tin cá nhân của bạn khi đăng ký.';
$l['d3_document'] = 'MyBB sử dụng cookies để giúp bạn biết thông tin đăng nhập nếu bạn là thành viên hoặc lần truy cập gần đây nhất nếu không phải là thành viên.
<br/><br/>Cookies là một tài liệu nhỏ chứa trong máy của bạn, cookies tạo bởi diễn đàn chỉ có thể sử dụng bởi diễn đàn và không có yêu cầu về bảo mật.
<br/><br/>Cookies trên diễn đàn có thể cho biết chủ đề nào bạn đã đọc và lần đọc cuối cùng của bạn.
<br/><br/>Để xoá toàn bộ cookies, bạn có thể bấm <a href="misc.php?action=clearcookies&amp;my_post_key={1}">vào đây</a>.';
$l['d4_name'] = 'Đăng nhập và đăng xuất';
$l['d4_desc'] = 'Làm cách nào để đăng nhập và đăng xuất.';
$l['d4_document'] = 'Khi bạn đăng nhập, bạn đã tạo cookie trên máy của bạn và bạn có thể duyệt diễn đàn mà không cần phải nhập tên và mật khẩu nữa. Khi bạn đăng xuất, bạn đã xoá cookie đó đi.
<br /><br />Để đăng nhập, đơn giản nhất là bấm vào nút đăng nhập phía trên bên phải của diễn đàn. Để đăng xuất, bấm vào nút thoát phía trên bên trái diễn đàn. Trong khi có sự kiện bạn không thể đăng xuất, nhưng nếu bạn xoá cookie trong máy thì bạn đã đăng xuất.';
$l['d5_name'] = 'Viết bài mới';
$l['d5_desc'] = 'Bắt đầu chủ đề mới trong diễn đàn.';
$l['d5_document'] = 'Khi đến diễn đàn, bạn cảm thấy thích thú và muốn tạo một chủ đề mới, cách đơn giản nhất là bấm vào nút "Tạo chủ đề" ở phía trên hoặc phía dưới của diễn đàn. Bạn nên chú ý là có thể bạn sẽ không được phép viết bài mới ở trong diễn đàn do người quản lý đã không cho phép.';
$l['d6_name'] = 'Viết trả lời';
$l['d6_desc'] = 'Trả lời chủ đề trong diễn đàn.';
$l['d6_document'] = 'Trong những chủ đề bạn xem sẽ có những chủ đề bạn muốn trả lời. Để làm điều đó cách đơn giản nhất là bấm vào nút "Trả lời" ở phía trên và dưới chủ đề. Chú ý là có thể người quản trị sẽ không cho phép bạn viết bài trả lời vì một số lý do nào đó.
<br /><br />Thêm nữa, có thể người quản lý đã đóng chủ đề đó, điều đó có nghĩa không thành viên nào có thể trả lời trong chủ đề đó.';
$l['d7_name'] = 'MyCode';
$l['d7_desc'] = 'Học cách sử dụng MyCode để viết bài.';
$l['d7_document'] = 'Bạn có thể sử dụng MyCode, một vài ví dụ về MyCode được sử dụng.
<p><br />[b]Đây là chữ tô đậm[/b]<br />&nbsp;&nbsp;&nbsp;<b>Đây là chữ tô đậm</b>
<p>[i]Đây là chữ in nghiêng[/i]<br />&nbsp;&nbsp;&nbsp;<i>Đây là chữ in nghiêng</i>
<p>[u]Đây là chữ gạch chân[/u]<br />&nbsp;&nbsp;&nbsp;<u>Đây là chữ gạch chân</u>
<p>[s]Đây là chữ gạch bỏ[/s]<br />&nbsp;&nbsp;&nbsp;<strike>Đây là chữ gạch bỏ</strike>
<p><br />[url]http://www.example.com/[/url]<br />&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">http://www.example.com/</a>
<p>[url=http://www.example.com/]Example.com[/url]<br />&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">Example.com</a>
<p>[email]example@example.com[/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">example@example.com</a>
<p>[email=example@example.com]E-mail Me![/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">E-mail Me!</a>
<p>[email=example@example.com?subject=spam]E-mail với tiêu đề[/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com?subject=spam">E-mail với tiêu đề</a>
<p><br />[quote]Chữ trích dẫn sẽ ở đây[/quote]<br />&nbsp;&nbsp;&nbsp;<quote>Chữ trích dẫn ở đây</quote>
<p>[code]Chữ giữ nguyên định dạng[/code]<br />&nbsp;&nbsp;&nbsp;<code>Chữ giữ nguyên định dạng</code>
<p><br />[img]http://www.php.net/images/php.gif[/img]<br />&nbsp;&nbsp;&nbsp;<img src="http://www.php.net/images/php.gif">
<p>[img=50x50]http://www.php.net/images/php.gif[/img]<br />&nbsp;&nbsp;&nbsp;<img src="http://www.php.net/images/php.gif" width="50" height="50">
<p><br />[color=red]Đây là chữ màu đỏ[/color]<br />&nbsp;&nbsp;&nbsp;<font color="red">Đây là chữ màu đỏ</font>
<p>[size=3]Chữ có kích thước là 3[/size]<br />&nbsp;&nbsp;&nbsp;<font size="3">Chữ có kích thước là 3</font>
<p>[font=Tahoma]Chữ dùng font Tahoma[/font]<br />&nbsp;&nbsp;&nbsp;<font face="Tahoma">Chữ dùng font Tahoma</font>
<p><br />[align=center]Canh giữa[/align]<div align="center">Canh giữa</div>
<p>[align=right]Canh bên phải[/align]<div align="right">Canh bên phải</div>
<p><br />[list]<br />[*]List Item #1<br />[*]List Item #2<br />[*]List Item #3<br />[/list]<br /><ul><li>List item #1</li><li>List item #2</li><li>List Item #3</li>
</ul>
<p>Bạn có thể làm danh sách bằng cách sử dụng [list=1] đối với số, và [list=a] đối với chữ.</p>';
