<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:55:02 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Thống kê';
$l['new_posts'] = 'Có bài mới';
$l['no_new_posts'] = 'Chưa có bài mới';
$l['forum_locked'] = 'Diễn đàn bị khóa';
$l['forum_unapproved_posts_count'] = 'Hiện tại có {1} bài viết chưa được phê duyệt trong diễn đàn này.';
$l['forum_unapproved_post_count'] = 'Hiện tại có 1 bài viét chưa được phê duyệt trong diễn đàn này.';
$l['forum_unapproved_threads_count'] = 'Hiện tại có {1} chủ đề chưa được phê duyệt trong diễn đàn này.';
$l['forum_unapproved_thread_count'] = 'Hiện tại có 1 chủ đề chưa được phê duyệt trong diễn đàn này.';
$l['markread'] = 'Đánh dấu tất cả là đã đọc';
$l['forumteam'] = 'Đội ngũ điều hành';
$l['forumstats'] = 'Thống kê diễn đàn';
$l['todays_birthdays'] = 'Sinh nhất trong ngày';
$l['birthdayhidden'] = 'Ẩn';
$l['quick_login'] = 'Đăng nhập:';
$l['index_logout'] = 'Thoát';
$l['private_messages'] = 'Tin nhắn';
$l['pms_new'] = 'Bạn có {1} tin nhắn mới.';
$l['pms_unread_total'] = '(Bạn có {1} tin nhắn chưa đọc và {2} thông điệp trong tất cả các thư mục của bạn.)';
$l['stats_posts_threads'] = 'Diễn đàn hiện có tổng cộng {1} bài viết trong {2} chủ đề.';
$l['stats_numusers'] = 'Số thành viên đã kích hoạt {1}.';
$l['stats_newestuser'] = 'Chào mừng thành viên mới nhất của diễn đàn, <b>{1}</b>';
$l['stats_mostonline'] = 'Truy cập nhiều nhất {1}, {2} lúc {3}';
$l['whos_online'] = 'Ai đang trực tuyến';
$l['complete_list'] = 'Danh sách hoàn chỉnh';
$l['online_online_plural'] = 'thành viên';
$l['online_online_singular'] = 'thành viên';
$l['online_member_plural'] = 'thành viên';
$l['online_member_singular'] = 'thành viên';
$l['online_anon_plural'] = 'are';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = 'Khách';
$l['online_guest_singular'] = 'Khách';
$l['online_note'] = '{1} {2} đã hoạt động tích cực trong vòng {3} phút vừa qua ({4} {5}, {6}/{7} người đang ẩn, và {8} {9}).';
$l['subforums'] = '<strong>Diễn đàn con:</strong>';
$l['bbclosed_warning'] = 'Diễn đàn của bạn được thiết đặt đóng';
$l['forum_closed'] = 'Diễn đàn đã đóng';
$l['board_stats_link_separator'] = ' | ';
