<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:58:59 +0000
// --------------------------------------------------------------------------------

$l['nav_register'] = 'Đăng ký';
$l['nav_activate'] = 'Kích hoạt';
$l['nav_resendactivation'] = 'Gửi lại email kích hoạt';
$l['nav_lostpw'] = 'Phục hồi mật khẩu';
$l['nav_resetpassword'] = 'Đổi mật khẩu';
$l['nav_login'] = 'Đăng nhập';
$l['nav_emailuser'] = 'Email';
$l['nav_profile'] = 'Hồ sơ của {1}';
$l['tpp_option'] = 'Hiện{1} chủ đề trong mỗi trang';
$l['ppp_option'] = 'Hiện {1} bài viết trong mỗi trang';
$l['account_activation'] = 'Kích hoạt tài khoản';
$l['activate_account'] = 'Kích hoạt tài khoản';
$l['activation_code'] = 'Mã kích hoạt:';
$l['email_user'] = 'Gửi tới {1} một Email';
$l['email_subject'] = 'Tiêu đề Email';
$l['email_message'] = 'Nội dung Email';
$l['send_email'] = 'Gửi Email';
$l['error_hideemail'] = 'Người nhận đã chọn ẩn địa chỉ email của họ và bạn không thể gửi email cho họ.';
$l['error_no_email_subject'] = 'Bạn cần phải nhập tiêu đề cho email của bạn';
$l['error_no_email_message'] = 'Bạn cần phải nhập nội dung cho email của bạn';
$l['login'] = 'Đăng nhập';
$l['pw_note'] = 'Hãy chú ý mật khẩu cần được bảo mật thật tốt.';
$l['lostpw_note'] = 'Quên mật khẩu?';
$l['lost_pw'] = 'Quên mật khẩu';
$l['lost_pw_form'] = 'Yêu cầu mật khẩu';
$l['email_address'] = 'Địa chỉ Email:';
$l['request_user_pass'] = 'Lấy lại mật khẩu';
$l['profile'] = 'Hồ sơ của {1}';
$l['registration_date'] = 'Ngày đăng ký:';
$l['date_of_birth'] = 'Ngày sinh:';
$l['birthdayhidden'] = 'Ẩn';
$l['birthday'] = 'Sinh nhật:';
$l['local_time'] = 'Giờ địa phương:';
$l['local_time_format'] = '{1} @ {2}';
$l['users_forum_info'] = 'Thông tin của {1}';
$l['joined'] = 'Gia nhập:';
$l['lastvisit'] = 'Hoạt động cuối:';
$l['total_posts'] = 'Tổng số bài viết:';
$l['ppd_percent_total'] = '{1} bài viết một ngày | {2} % trong tổng số bài viết';
$l['total_threads'] = 'Tổng số chủ đề:';
$l['tpd_percent_total'] = '{1} chủ đề một ngày | {2} % trong tổng số chủ đề';
$l['find_posts'] = 'Tìm tất cả bài viết';
$l['find_threads'] = 'Tìm tất cả bài chủ đề';
$l['members_referred'] = 'Người giới thiệu:';
$l['rating'] = 'Đánh giá:';
$l['users_contact_details'] = 'Thông tin liên lạc của {1}';
$l['homepage'] = 'Trang chủ:';
$l['pm'] = 'Tin nhắn cá nhân:';
$l['send_pm'] = 'Gửi tin nhắn cho {1}.';
$l['icq_number'] = 'ICQ:';
$l['aim_screenname'] = 'AIM:';
$l['yahoo_id'] = 'Yahoo ID:';
$l['skype_id'] = 'Skype ID:';
$l['google_id'] = 'Google Talk ID:';
$l['avatar'] = 'Avatar:';
$l['warning_level'] = 'Cảnh Cáo:';
$l['warn'] = 'Báo cáo';
$l['away_note'] = '{1} đang làm.';
$l['away_reason'] = 'Nguyên nhân:';
$l['away_since'] = 'Từ xa:';
$l['away_returns'] = 'Trả về:';
$l['away_no_reason'] = 'Không xác định.';
$l['ban_note'] = 'Tài khoản diễn đàn này hiện bị cấm.';
$l['ban_by'] = 'Banned Bởi';
$l['ban_length'] = 'Thời gian';
$l['ban_remaining'] = 'remaining';
$l['users_additional_info'] = 'Thông tin cá nhân của {1}';
$l['email'] = 'Email:';
$l['send_user_email'] = 'Gửi cho {1} 1 email.';
$l['users_signature'] = 'Chữ ký của {1}';
$l['agreement'] = 'Điều khoản đăng ký';
$l['agreement_1'] = 'Chúng tôi đã cố gắng để chỉnh sửa hoặc loại bỏ những bài viết không phù hợp như: định hướng tình dục, lạm dụng, hận thù, vu khống, hoặc thông tin có thể được coi là xâm phạm sự riêng tư của một người, hoặc mang tính chất đe dọa. Tuy nhiên chúng tôi không thể đảm bảo có thể xem xét tất cả các tin được đăng trên hệ thống thảo luận này. Vì lý do này, bạn đồng ý rằng tất cả các thông tin bạn đăng trên hệ thống thảo luận này thể hiện các quan điểm và ý kiến ​​của cá nhân bạn và không phải là quan điểm của diễn đàn. Vì vậy chúng tôi không chịu trách nhiệm cho bất kỳ bài viết nào của thành viên. Chúng tôi không xác minh hoặc đảm bảo tính chính xác và đầy đủ của mỗi bài viết.';
$l['agreement_2'] = 'Bằng cách đăng ký vào hệ thống thảo luận này, bạn đồng ý rằng bạn sẽ không gửi các tài liệu sai phạm, không chính xác, lăng mạ, hận thù, quấy rối, định hướng tình dục, đe doạ hoặc xâm phạm sự riêng tư của một người, hoặc bất kỳ các tài liệu nào có thể vi phạm pháp luật.';
$l['agreement_3'] = 'Việc không tuân thủ các quy định có thể dẫn đến việc chấm dứt tài khoản của bạn, hệ thống sẽ treo tài khoản của bạn, hoặc cấm vĩnh viễn quyền truy cập vào diễn đàn. Địa chỉ IP của bạn được ghi lại với từng đăng bài bạn thực hiện trên hệ thống của chúng tôi và có thể sẽ được cung cấp cho nhà chức trách khi cần thiết. Bạn đồng ý rằng chúng tôi có quyền gỡ bỏ, sửa, hoặc khóa bất kỳ tài khoản hay các bài viết bất cứ lúc nào nếu nó không phù hợp. Bạn cũng đồng ý rằng bất kỳ thông tin nào mà bạn nhập vào hệ thống sẽ lưu trữ trong cơ sở dữ liệu, và rằng "cookies" được lưu trữ trên máy tính của bạn để lưu thông tin đăng nhập của bạn. ';
$l['agreement_4'] = 'Bất kỳ thông tin nào mà bạn cung cấp trên diễn đàn sẽ không được tiết lộ cho bên thứ ba mà không có sự đồng ý hoàn toàn của bạn, tuy nhiên chúng tôi sẽ không chịu trách nhiệm khi cơ sở dữ liệu bị hacker tấn công.';
$l['agreement_5'] = 'Bằng cách tiếp tục quá trình đăng ký, bạn đã đồng ý với các quy định nêu trên của chúng tôi.';
$l['registration'] = 'Đăng ký';
$l['required_fields'] = 'Phần bắt buộc';
$l['complex_password'] = 'Mật khẩu <acronym title="Một mật khẩu có độ dài ít nhất {1} ký tự và có chứa chữ hoa, mchữ thường và số.">phức tạp</acronym>:';
$l['confirm_email'] = 'Xác nhận Email:';
$l['optional_fields'] = 'Thông tin thêm';
$l['website_url'] = 'URL Website:';
$l['birthdate'] = 'Ngày sinh:';
$l['additional_info'] = 'Các thông tin khác';
$l['required_info'] = 'Thông tin bắt buộc';
$l['i_agree'] = 'Đồng ý';
$l['account_details'] = 'Chi tiết tài khoản';
$l['account_prefs'] = 'Thiết lập tài khoản:';
$l['invisible_mode'] = 'Ẩn với mọi người.';
$l['allow_notices'] = 'Nhận email từ BQT.';
$l['hide_email'] = 'Ẩn email với thành viên khác.';
$l['email_notify'] = 'Tự động theo dõi bài viết.';
$l['receive_pms'] = 'Nhận tin nhắn từ thành viên khác.';
$l['pm_notice'] = 'Thông báo cho bạn khi có tin nhắn mới.';
$l['email_notify_newpm'] = 'Thông báo cho bạn qua email khi có tin nhắn mới.';
$l['time_offset'] = 'Múi giờ (<acronym title="Daylight Saving Time">DST</acronym> correction excluded):';
$l['time_offset_desc'] = 'Nếu bạn sống ở một múi giờ khác với những gì bảng này thiết lập, bạn có thể chọn nó từ danh sách dưới đây.';
$l['dst_correction'] = 'Hiệu chỉnh Daylight Saving Time:';
$l['dst_correction_auto'] = 'Tự động phát hiện các thiết lập DST';
$l['dst_correction_enabled'] = 'Luôn luôn sử dụng DST';
$l['dst_correction_disabled'] = 'Không bao giờ sử dụng DST';
$l['redirect_registered_coppa_activate'] = 'Cảm ơn bạn đã đăng ký thành viên {1}, {2}. Tài khoản của bạn đã được tạo, tuy nhiên chủ sở hữu của tài khoản này ở độ tuổi dưới 13, vì vậy bạn cần sự cho phép của cha mẹ cần trước khi tài khoản này được phép sử dụng.<br /><br />Phụ huynh hoặc người giám hộ hợp pháp của bạn sẽ cần phải tải về, điền và gửi cho chúng tôi một bản sao hoàn chỉnh của <a href="member.php?action=coppa_form">Điều khoản COPPA (Đạo luật bảo vệ bảo mật trực tuyến của trẻ em)</a>.<br /><br />Sau khi chúng tôi nhận được bản sao hoàn chỉnh của giấy phép này, tài khoản của bạn sẽ được kích hoạt.';
$l['coppa_compliance'] = 'Giấy phép COPPA';
$l['coppa_desc'] = 'Để đăng ký trên các diễn đàn, chúng tôi yêu cầu bạn xác minh tuổi của bạn theo quy định <a href="http://coppa.org/" title="Đạo luật bảo vệ bảo mật trực tuyến của trẻ em" target="_blank">COPPA (Đạo luật bảo vệ bảo mật trực tuyến của trẻ em)</a>. Vui lòng nhập ngày sinh của bạn.<br /><br />Nếu bạn chưa đủ 13 tuổi, bạn cần sự cho phép của phụ huynh để tiếp tục đăng ký. Phụ huynh của bạn cần phải tải về và điền vào giấy phép <a href="member.php?action=coppa_form" target="_blank">COPPA (Đạo luật bảo vệ bảo mật trực tuyến của trẻ em)</a> sau đó gửi lại cho chúng tôi.';
$l['hide_dob'] = 'Bạn có thể ẩn ngày sinh và tuổi của bạn bằng cách chỉnh sửa hồ sơ của bạn sau khi đăng ký.';
$l['signature'] = 'Chữ ký:';
$l['continue_registration'] = 'Tiếp tục đăng ký';
$l['birthdayprivacy'] = 'Bảo mật ngày sinh:';
$l['birthdayprivacyall'] = 'Hiện tuổi và ngày sinh';
$l['birthdayprivacynone'] = 'Ẩn tuổi và ngày sinh';
$l['birthdayprivacyage'] = 'Chỉ hiện tuổi';
$l['leave_this_field_empty'] = 'Để trống mục này:';
$l['error_need_to_be_thirteen'] = 'Để đăng ký làm thành viên của diễn đàn bạn phải lớn hơn 13 tuổi.';
$l['coppa_registration'] = 'Điều khoản COPPA';
$l['coppa_form_instructions'] = 'Xin vui lòng in mẫu dưới đây, và gửi tới số Fax ở dưới hoặc gửi email tới email của chúng tôi.';
$l['fax_number'] = 'Số Fax:';
$l['mailing_address'] = 'Địa chỉ liên lạc:';
$l['account_information'] = 'Thông tin tài khoản';
$l['parent_details'] = 'Thông tin người giám hộ';
$l['full_name'] = 'Tên đầy đủ:';
$l['relation'] = 'Mối quan hệ:';
$l['phone_no'] = 'Số điện thoại #:';
$l['coppa_parent_agreement'] = 'Tôi cam kết những thông tin mà tôi cung cấp là đúng sự thật, tài khoản có thể bị xóa bỏ bất cứ khi nào nếu yêu cầu.';
$l['coppa_agreement_1'] = 'Người sử dụng dưới 13 tuổi phải nhận được sự cho phép của cha mẹ hoặc người giám hộ hợp pháp để đăng ký trên {1}.';
$l['coppa_agreement_2'] = 'Phụ huynh hoặc người giám hộ hợp pháp sẽ cần phải tải về, điền vào và gửi cho chúng tôi một bản sao của <a href="member.php?action=coppa_form" target="_blank">Đạo luật COPPA </a> trước khi thành viên được kích hoạt.';
$l['coppa_agreement_3'] = 'Nếu bạn muốn, bạn có thể bắt đầu thủ tục đăng ký ngay bây giờ, tuy nhiên tài khoản của bạn sẽ không thể truy cập cho đến khi chúng tôi nhận được đơn đăng kí.';
$l['error_invalid_birthday'] = 'Ngày sinh bạn đã nhập không hợp lệ. Vui lòng nhập ngày sinh hợp lệ.';
$l['error_awaitingcoppa'] = 'Bạn không thể đăng nhập bằng tài khoản này vì nó vẫn đang chờ xác nhận COPPA của cha mẹ hoặc người giám hộ.<br /><br />Phụ huynh hoặc người giám hộ hợp pháp sẽ cần phải tải về, điền vào và gửi cho chúng tôi một bản sao <a href="member.php?action=coppa_form">Đạo luật COPPA </a> của chúng tôi.<br /><br />Sau khi chúng tôi nhận được một bản sao của mẫu đơn này, tài khoản sẽ được kích hoạt.';
$l['lang_select'] = 'Cài đặt ngôn ngữ:';
$l['lang_select_desc'] = 'Bạn có thể chọn ngôn ngữ mà mình sử dụng để thuận tiện khi hoạt động tại diễn đàn.';
$l['lang_select_default'] = 'Mặc định';
$l['submit_registration'] = 'Đăng ký!';
$l['confirm_password'] = 'Xác nhận mật khẩu:';
$l['referrer'] = 'Người giới thiệu:';
$l['referrer_desc'] = 'Nếu bạn được ai đó giới thiệu vào đây, bạn có thể ghi tên trong diễn đàn của họ. Nếu không có, xin vui lòng bỏ trống.';
$l['resend_activation'] = 'Kích hoạt lại tài khoản';
$l['request_activation'] = 'Yêu cầu mã kích hoạt';
$l['ppp'] = 'Bài viết trên mỗi trang:';
$l['ppp_desc'] = 'Cho phép bạn chọn số lượng các bài viết được hiển thị trên mỗi trang trong một chủ đề';
$l['tpp'] = 'Chủ đề trên mỗ trang:';
$l['tpp_desc'] = 'Cho phép bạn chọn số chủ đề sẽ được hiển thị trên mỗi trang trong danh sách chủ đề.';
$l['reset_password'] = 'Đặt lại mật khẩu';
$l['send_password'] = 'Gửi mật khẩu mới!';
$l['registration_errors'] = 'Đã xảy ra lỗi với đăng ký của bạn:';
$l['timeonline'] = 'Thời gian online:';
$l['timeonline_hidden'] = '(Ẩn)';
$l['registrations_disabled'] = 'Xin lỗi, nhưng bạn không thể đăng ký tại thời điểm này vì người quản trị đã vô hiệu hóa đăng ký tài khoản mới.';
$l['error_username_length'] = 'Tên đăng nhập của bạn là không hợp lệ Tên người dùng có được trong vòng {1} để {2} ký tự..';
$l['error_stop_forum_spam_spammer'] = 'Xin lỗi, bạn {1} phù hợp với một spammer mà chúng tối biết. Nếu bạn cảm thấy đây là một lỗi của hệ thống, xin vui lòng liên hệ với quản trị viên. ';
$l['error_stop_forum_spam_fetching'] = 'Xin lỗi, một lỗi đã xảy ra dẫn đến hệ thống nhận định tài khoản của bạn nằm trong một cơ sở dữ liệu spammer. Nhiều khả năng kết nối tới cơ sở dữ liệu đã xảy ra sự cố. Vui lòng thử lại sau. ';
$l['none_registered'] = 'Không đăng ký';
$l['not_specified'] = 'Không rõ';
$l['membdayage'] = '({1} tuổi)';
$l['mod_options'] = 'Công cụ Moderator';
$l['edit_in_mcp'] = 'Chỉnh sửa hồ sơ này trong ModCP';
$l['ban_in_mcp'] = 'Cấm người dùng này trong ModCP';
$l['purgespammer'] = 'Lọc Spammer';
$l['edit_usernotes'] = 'Chỉnh sửa ghi chú người dùng trong ModCP';
$l['no_usernotes'] = 'Hiện tại không có ghi chú về người này';
$l['view_all_notes'] = 'Xem tất cả các ghi chú';
$l['view_notes_for'] = 'Xem ghi chú cho {1}';
$l['reputation'] = 'Danh tiếng:';
$l['reputation_vote'] = 'Đánh giá';
$l['reputation_details'] = 'Chi tiết';
$l['already_logged_in'] = 'Thông báo: Bạn đã đăng nhập như {1}';
$l['admin_edit_in_acp'] = 'Chỉnh sửa người dùng này trong AdminCP';
$l['admin_ban_in_acp'] = 'Cấm người dùng này trong AdminCP';
$l['admin_options'] = 'Công cụ Administrator';
$l['redirect_registered_activation'] = 'Cảm ơn bạn đã đăng ký trên {1}, {2}. <P> Để hoàn tất đăng ký của bạn, xin vui lòng kiểm tra email của bạn để được hướng dẫn kích hoạt tài khoản. Trước khi bạn tài khoản của bạn được kích hoạt, bạn sẽ không thể đăng bài trên diễn đàn';
$l['redirect_emailupdated'] = 'Email của bạn đã được thay đổi thành công <br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['redirect_accountactivated'] = 'Tài khoản của bạn đã được kích hoạt .<br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['redirect_accountactivated_admin'] = 'Email của bạn được đã xác nhận thành công. <br /> Tài khoản của bạn bây giờ phải được kích hoạt bởi một quản trị viên. Trước khi bạn tài khoản của bạn được kích hoạt, bạn sẽ không thể đăng bài trên diễn đàn. <br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['redirect_registered'] = 'Cảm ơn bạn đã đăng ký trên {1}, {2} <br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['redirect_registered_admin_activate'] = 'Cảm ơn bạn đã đăng ký trên {1}, {2}. <br /> Tài khoản của bạn phải được kích hoạt bởi một quản trị viên. Trước khi bạn tài khoản của bạn được kích hoạt, bạn sẽ không thể đăng bài trên diễn đàn.';
$l['redirect_loggedout'] = 'Bạn đã đăng xuất thành công.<br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['redirect_alreadyloggedout'] = 'Bạn đã đăng xuất hoặc chưa đăng nhập. <br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['redirect_lostpwsent'] = 'Cảm ơn bạn, bạn sẽ nhận được một email với các hướng dẫn để thiết lập lại mật khẩu. <br /> <br /> Bây giờ bạn sẽ được đưa trở lại trang chủEmail kích hoạt của bạn đã được gửi lại';
$l['redirect_activationresent'] = 'Email kích hoạt của bạn đã được gửi lại';
$l['redirect_passwordreset'] = 'Cảm ơn bạn, mật khẩu cho tài khoản của bạn đã được thiết lập lại, mật khẩu mới được tạo ra một cách ngẫu nhiên đã được gửi đến địa chỉ email của bạn.';
$l['redirect_memberrated'] = 'Đánh giá thành viên thành công.';
$l['redirect_registered_passwordsent'] = 'Một mật khẩu ngẫu nhiên đã được tạo ra và gửi đến địa chỉ email của bạn. Trước khi đăng nhập vào diễn đàn, bạn sẽ cần phải kiểm tra email của bạn để mật khẩu.';
$l['redirect_validated'] = 'Cảm ơn bạn, tài khoản của bạn đã được xác nhận <br /> Bây giờ bạn sẽ được đưa trở lại trang chủ.';
$l['error_activated_by_admin'] = 'Bạn không thể gửi lại email kích hoạt tài khoản của bạn bởi vì tất cả các tài khoản cần phải được chấp thuận bởi một quản trị viên';
$l['error_alreadyregistered'] = 'Xin lỗi, nhưng hệ thống của chúng tôi cho thấy rằng bạn đã đăng ký trên diễn đàn và việc đăng ký nhiều tài khoản đã bị vô hiệu hóa.';
$l['error_alreadyregisteredtime'] = 'Chúng tôi không thể xử lý đăng ký của bạn vì đã có sự {1} đăng ký mới (s) từ địa chỉ ip của bạn trong quá khứ {2} giờ, hãy thử lại sau.';
$l['error_badlostpwcode'] = 'Bạn đã nhập mã reset mật khẩu không hợp lệ. Xin hãy đọc lại email hoặc liên hệ với quản trị viên diễn đàn để được giúp đỡ.';
$l['error_badactivationcode'] = 'Bạn đã nhập mã kích hoạt tài khoản không hợp lệ. Để gửi lại email kích hoạt, xin vui lòng bấm vào <a href="member.php?action=resendactivation">đây </a>.';
$l['error_alreadyactivated'] = 'Nó xuất hiện tài khoản của bạn đã được kích hoạt hoặc không yêu cầu xác minh email.';
$l['error_alreadyvalidated'] = 'email của bạn đã được xác nhận.';
$l['error_nothreadurl'] = 'Thông điệp của bạn không chứa các URL của chủ đề. Vui lòng sử dụng tính năng "Gửi cho bạn bè" để gửi chủ đề.';
$l['error_bannedusername'] = 'Bạn đã nhập một tên đăng nhập bị cấm sử dụng, hãy chọn tên đăng nhập khác.';
$l['error_notloggedout'] = 'ID của bạn có thể không được xác nhận đăng nhập. Điều này có thể là bởi vì một Javascript độc hại đang cố gắng đăng nhập một cách tự động vào tài khoản của bạn. Nếu bạn có ý định thoát ra, hãy nhấp vào nút Thoát ở menu trên cùng. ';
$l['error_regimageinvalid'] = 'Mã xác nhận hmà bạn đã nhập không chính xác. Vui lòng nhập chính xác những gì xuất hiện trong hình ảnh.';
$l['error_regimagerequired'] = 'Xin vui lòng điền mã xác nhận để tiếp tục quá trình đăng nhập. Vui lòng nhập chính xác những gì xuất hiện trong hình ảnh.';
$l['error_spam_deny'] = 'Hệ thống của chúng tôi phát hiện rằng bạn có thể là một spammer vì vậy đăng ký của bạn đã bị từ chối. Nếu bạn cảm thấy đây là một lỗi của hệ thống, xin vui lòng liên hệ với người quản trị.';
$l['error_spam_deny_time'] = 'Hệ thống của chúng tôi phát hiện rằng bạn có thể là một spammer vì vậy đăng ký của bạn đã bị từ chối. Đăng ký phải mất một thời gian tối thiểu là {1} giây để ngăn chặn phần mềm đăng ký tự động, bạn đăng ký mất {2} giây. Nếu bạn cảm thấy đây là một lỗi của hệ thống, xin vui lòng liên hệ với người quản trị. ';
$l['js_validator_no_username'] = 'Bạn phải nhập tên đăng nhập';
$l['js_validator_invalid_email'] = 'Bạn cần phải nhập một địa chỉ email hợp lệ';
$l['js_validator_email_match'] = 'Bạn cần phải nhập lại địa chỉ email một lần nữa';
$l['js_validator_no_image_text'] = 'Bạn cần phải nhập dòng chữ trong hình ảnh trên';
$l['js_validator_no_security_question'] = 'Bạn cần phải nhập câu trả lời cho câu hỏi trên';
$l['js_validator_password_matches'] = 'Mật khẩu bạn nhập phải phù hợp';
$l['js_validator_password_complexity'] = 'Kiểm tra mật khẩu phức tạp';
$l['js_validator_password_length'] = 'Mật khẩu của bạn phải có từ {1} ký tự trở lên';
$l['js_validator_not_empty'] = 'Bạn phải chọn hoặc nhập giá trị cho lĩnh vực này';
$l['js_validator_checking_username'] = 'Kiểm tra nếu tên đăng nhập đã tồn tại';
$l['js_validator_username_length'] = 'Tên người dùng có chứa từ {1} tới {2} ký tự';
$l['js_validator_checking_referrer'] = 'Kiểm tra nếu tên người giới thiệu tồn tại';
$l['js_validator_captcha_valid'] = 'Kiểm tra xem bạn nhập mã xác minh có chính xác không.';
$l['security_question'] = 'Câu hỏi bảo mật';
$l['question_note'] = 'Hãy trả lời những câu hỏi được cung cấp để ngăn chặn các quá trình tự động đăng ký.';
$l['error_question_wrong'] = 'Câu trả lời mà bạn cung cấp không đúng. Vui lòng thử lại.';
$l['subscription_method'] = 'Chế độ theo dõi mặc định:';
$l['no_auto_subscribe'] = 'Không theo dõi';
$l['no_subscribe'] = 'Không nhận thông báo';
$l['instant_email_subscribe'] = 'Nhận email thông báo';
$l['instant_pm_subscribe'] = 'Nhận thông báo quan tin nhắn';
$l['remove_from_buddy_list'] = 'Xóa khỏi danh sách bạn bè';
$l['add_to_buddy_list'] = 'Thêm vào danh sách bạn bè';
$l['remove_from_ignore_list'] = 'Xóa khỏi danh sách bỏ qua';
$l['add_to_ignore_list'] = 'Thêm vào danh sách bỏ qua';
$l['report_user'] = 'Báo cáo người dùng';
$l['newregistration_subject'] = 'Có đăng ký mới tại {1}';
$l['newregistration_message'] = '{1},

Có một người dùng mới tại {2} đang chờ được kích hoạt.

Tên đăng nhập: {3}

Cảm ơn,
{2} QTV';
$l['nav_referrals'] = 'Người dùng được giới thiệu bởi {1}';
$l['referrals'] = 'Giới thiệu';
$l['referral_date'] = 'Ngày giới thiệu:';
$l['referrals_no_user_specified'] = 'Không có người dùng chỉ định.';
$l['referrals_invalid_user'] = 'Người dùng được chỉ định không hợp lệ.';
$l['member_no_referrals'] = 'Không có giới thiệu cho người dùng này.';
$l['coppa_desc_for_deny'] = 'Để đăng ký trên các diễn đàn này, chúng tôi yêu cầu bạn xác minh tuổi của mình để tuân thủ <a href="https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule" title="Children\'s Online Privacy Protection Act" target="_blank" rel="noopener">COPPA</a>. Vui lòng nhập ngày sinh của bạn dưới đây.';
$l['edit_ban_in_mcp'] = 'Chỉnh sửa lệnh cấm trong Mod CP';
$l['lift_ban_in_mcp'] = 'Nâng lệnh cấm trong Mod CP';
$l['registration_ip'] = 'Đăng ký IP:';
$l['last_known_ip'] = 'IP nhập lần cuối cùng:';
$l['admin_lift_ban_in_acp'] = 'Nâng lệnh cấm trong Admin CP';
$l['admin_edit_ban_in_acp'] = 'Chỉnh sửa lệnh cấm trong Admin CP';
$l['js_validator_bad_password_security'] = 'Mật khẩu bạn đã nhập tương tự như tên người dùng hoặc địa chỉ email của bạn. Vui lòng nhập một mật khẩu mạnh hơn.';
