<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 13:59:30 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Danh sách thành viên';
$l['memberlist_disabled'] = 'Danh sách thành viên đã bị vô hiệu hóa bởi Administrator.';
$l['member_list'] = 'Danh sách thành viên';
$l['avatar'] = 'Avatar';
$l['username'] = 'Username';
$l['joined'] = 'Tham gia';
$l['lastvisit'] = 'Hoạt động cuối';
$l['posts'] = 'Số bài viết';
$l['threads'] = 'Số chủ đề';
$l['referrals'] = 'Đã gới thiệu';
$l['search_members'] = 'Tìm kiếm';
$l['website'] = 'Website';
$l['sort_by'] = 'Sắp xếp theo';
$l['contains'] = 'Có chứa:';
$l['sort_by_username'] = 'Sắp xếp theo: Username';
$l['sort_by_regdate'] = 'Sắp xếp theo: Ngày đăng ký';
$l['sort_by_lastvisit'] = 'Sắp xếp theo: Hoạt động cuối';
$l['sort_by_posts'] = 'Sắp xếp theo: Số bài viết';
$l['sort_by_threads'] = 'Sắp xếp theo: Số chủ đề';
$l['sort_by_referrals'] = 'Sắp xếp theo: Số thành viên đã giới thiệu';
$l['order_asc'] = 'Tăng dần';
$l['order_desc'] = 'Giảm dần';
$l['asc'] = 'Giảm dần';
$l['desc'] = 'Tăng dần';
$l['forumteam'] = 'Danh sách BQT';
$l['advanced_search'] = 'Tìm kiếm nâng cao';
$l['nav_memberlist_search'] = 'Tìm kiếm';
$l['search_member_list'] = 'Tìm kiếm danh sách thành viên';
$l['search_criteria'] = 'Điều kiện tìm kiếm';
$l['begins_with'] = 'Bắt đầu với';
$l['username_contains'] = 'Có chứa';
$l['search_website'] = 'Website URL';
$l['search_aim'] = 'Tài khoản AIM';
$l['search_skype'] = 'Tài khoản Skype';
$l['search_google'] = 'Tài khoản Google Talk';
$l['search_yahoo'] = 'Tài khoản Yahoo!';
$l['search_icq'] = 'Số ICQ';
$l['search_options'] = 'Tùy chọn tìm kiếm';
$l['per_page'] = 'Số kết quả trên một trang';
$l['search'] = 'Tìm kiếm';
$l['error_no_members'] = '<p>Không có thành viên nào phù hợp với yêu cầu tìm kiếm của bạn vào.</p><p>Vui lòng nhập một thuật ngữ tìm kiếm khác và thử lại.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
$l['exactly'] = 'Chính xác:';
$l['username_exact'] = 'chính xác';
