<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:02:19 +0000
// --------------------------------------------------------------------------------

$l['click_no_wait'] = 'Click vào đây nếu bạn không muốn chờ đợi lâu hơn.';
$l['redirect_return_forum'] = '<br /> <br /> Hoặc, có thể bấm <a href="{1}">vào đây</a> để quay trở lại diễn đàn.';
$l['redirect_emailsent'] = 'Tin nhắn e-mail của bạn đã được gửi thành công.';
$l['redirect_loggedin'] = 'Bạn đã đăng nhập thành công. <br /> Bây giờ bạn sẽ được đưa trở lại trang chủ..';
$l['error_invalidpworusername'] = 'Bạn đã nhập tên người dùng / mật khẩu không hợp lệ. <br /> <br /> Nếu bạn đã quên mật khẩu của bạn xin vui lòng <a href="member.php?action=lostpw"> lấy mật khẩu </a> mới.';
$l['error_invalidpworusername1'] = 'Bạn đã nhập email / mật khẩu không hợp lệ. <br /> <br /> Nếu bạn đã quên mật khẩu của bạn xin vui lòng <a href="member.php?action=lostpw"> lấy mật khẩu </a> mới.';
$l['error_invalidpworusername2'] = 'Bạn đã nhập tên người dùng / mật khẩu không hợp lệ hoặc sự kết hợp email / mật khẩu. <br /> <br /> Nếu bạn đã quên mật khẩu của bạn xin vui lòng <a href="member.php?action=lostpw"> lấy mật khẩu </a> mới.';
$l['error_incompletefields'] = 'Bạn chưa nhập đầy đủ thông tin cần thiết. Xin hãy quay lại và điền đầy đủ thông tin rồi tiếp tục.';
$l['error_alreadyuploaded'] = 'Bài đăng này đã chứa tệp đính kèm có tên "{1}". Vui lòng đổi tên tập tin và tải lại. Ngoài ra, bạn có thể nhấp vào "Cập nhật tệp đính kèm".';
$l['error_alreadyuploaded_perm'] = 'Bài này đã có một file đính kèm có cùng tên. Vui lòng loại bỏ các tập tin hiện có hoặc đổi tên tập tin và tải nó lên một lần nữa.';
$l['error_nomessage'] = 'Xin lỗi, chúng tôi không thể tiến hành bởi vì bạn đã nhập một email không hợp lệ. Xin vui lòng quay trở lại nhập vào email hợp lệ.';
$l['error_invalidemail'] = 'Bạn đã nhập một email không hợp lệ.';
$l['error_nomember'] = 'Thành viên mà bạn chỉ định không hợp lệ hoặc không tồn tại.';
$l['error_maxposts'] = 'Xin lỗi, nhưng số bài viết mỗi ngày của bạn đã vượt quá giới hạn. Xin vui lòng chờ cho đến ngày mai để tiếp tục đăng bài hoặc liên hệ với quản trị viên của bạn.<br /><br />Số bài viết tối đa của bạn trong 1 ngày là {1} bài.';
$l['error_nohostname'] = 'Không có tên máy chủ lưu trữ nào được tìm thấy cho IP mà bạn nhập vào.';
$l['error_invalidthread'] = 'Chủ đề không có thật.';
$l['error_invalidpost'] = 'Bài viết không hợp lệ';
$l['error_invalidannouncement'] = 'Thông báo không tồn tại.';
$l['error_invalidattachment'] = 'Đính kèm không hợp lệ';
$l['error_invalidforum'] = 'Diễn đàn không hợp lệ';
$l['error_closedinvalidforum'] = 'Bạn không thể đăng bài trong diễn đàn này hoặc nó đã bị đóng, hoặc đây là một phân loại diễn đàn.';
$l['error_attachtype'] = 'Kiểu tập tin mà bạn gửi kèm theo không được chấp nhận. Xin vui lòng xóa tập tin đính kèm hoặc chọn kiểu tập tin khác.';
$l['error_attachsize'] = 'Tập tin đính kèm "{1}" quá lớn. Dung lượng tối đa cho các loại hình tập tin đó là {2} kilobytes.';
$l['error_uploadempty'] = 'Tập tin "{1}" được chỉ định là rỗng.';
$l['error_uploadsize'] = 'Kích thước của tệp tin quá lớn.';
$l['error_uploadfailed'] = 'Các tập tin tải lên không thành công. Vui lòng chọn một tập tin hợp lệ và thử lại.';
$l['error_uploadfailed_detail'] = 'Chi tiết lỗi: ';
$l['error_uploadfailed_php1'] = 'Lỗi PHP: Tập tin được tải lên vượt quá sự chỉ thị upload_max_filesize trong php.ini. Xin vui lòng liên hệ với quản trị viên diễn đàn của bạn về lỗi này.';
$l['error_uploadfailed_php2'] = 'Tệp tin được tải lên vượt quá kích thước tập tin chỉ định.';
$l['error_uploadfailed_php3'] = 'Tệp tin chỉ được tải lên 1 phần.';
$l['error_uploadfailed_php4'] = 'Không có tập tin nào được tải lên.';
$l['error_uploadfailed_php6'] = 'Lỗi PHP: Thiếu một thư mục tạm thời. Xin vui lòng liên hệ với quản trị viên diễn đàn của bạn về lỗi này.';
$l['error_uploadfailed_php7'] = 'Lỗi PHP: Không thể ghi tập tin vào đĩa. Xin vui lòng liên hệ với quản trị viên diễn đàn của bạn về lỗi này.';
$l['error_uploadfailed_phpx'] = 'Lỗi PHP: {1}.  Xin vui lòng liên hệ với quản trị viên diễn đàn của bạn về lỗi này.';
$l['error_uploadfailed_nothingtomove'] = 'Một tập tin không hợp lệ đã được xác định, do đó, tệp tin được tải lên không thể được chuyển đến các nơi cần đến.';
$l['error_uploadfailed_movefailed'] = 'Có một vấn đề khi di chuyển tệp tin được tải lên đến các nơi cần đến.';
$l['error_uploadfailed_lost'] = 'Các tập tin đính kèm không thể được tìm thấy trên máy chủ.';
$l['error_emailmismatch'] = 'Địa chỉ email bạn nhập vào không phù hợp. Xin vui lòng quay lại và thử lại';
$l['error_nopassword'] = 'Bạn đã không nhập mật khẩu hợp lệ.';
$l['error_usernametaken'] = 'Tên người dùng mà bạn đã chọn đã được đăng ký. Nếu trước đó bạn đã đăng ký trên các diễn đàn, xin vui lòng <a href="member.php?action=login"> đăng nhập</a>.';
$l['error_nousername'] = 'Bạn đã không nhập tên người dùng.';
$l['error_invalidusername'] = 'Tên người dùng bạn đã nhập không hợp lệ.';
$l['error_invalidpassword'] = 'Mật khẩu bạn nhập không đúng. Nếu bạn đã quên mật khẩu của bạn, hãy nhấp <a href="member.php?action=lostpw"> vào đây </a>. Nếu không, quay trở lại và thử lại.';
$l['error_postflooding'] = 'Xin lỗi, nhưng hệ thống không thể xử lý bài viết của bạn. Các quản trị viên đã xác định bạn chỉ được phép đăng bài sau {1} giây.';
$l['error_nopermission_guest_1'] = 'Bạn chưa đăng nhập hoặc bạn không được phép xem trang này. Điều này có thể là bởi vì một trong những lý do sau:';
$l['error_nopermission_guest_2'] = 'Bạn chưa đăng nhập hoặc đăng ký. Xin vui lòng sử dụng biểu mẫu ở dưới cùng của trang này để đăng nhập.';
$l['error_nopermission_guest_3'] = 'Bạn không được phép truy cập vào trang này. Có phải bạn đang cố gắng truy cập vào các trang quản trị của Admin hoặc nhưng nơi bạn không nên vào? Hãy kiểm tra lại nội quy diễn đàn xem bạn được phép thực hiện thao tác này không.';
$l['error_nopermission_guest_4'] = 'Tài khoản của bạn có thể đã bị vô hiệu hóa bởi một quản trị viên, hoặc nó có thể đang chờ được kích hoạt.';
$l['error_nopermission_guest_5'] = 'Bạn đã truy cập trực tiếp trang này thay vì sử dụng các hình thức thích hợp hoặc liên kết.';
$l['login'] = 'Đăng nhập';
$l['need_reg'] = 'Cần phải đăng ký?';
$l['forgot_password'] = 'Quên mật khẩu?';
$l['error_nopermission_user_1'] = 'Bạn không được phép truy cập vào trang này. Điều này có thể là do một trong những lý do sau:';
$l['error_nopermission_user_ajax'] = 'Bạn không được phép truy cập vào trang này.';
$l['error_nopermission_user_2'] = 'Tài khoản của bạn đã bị treo hoặc bạn đã bị cấm truy cập tài nguyên này.';
$l['error_nopermission_user_3'] = 'Bạn không được phép truy cập vào trang này. Có phải bạn đang cố gắng truy cập vào các trang quản trị của Admin hoặc nhưng nơi bạn không nên vào? Hãy kiểm tra lại nội quy diễn đàn xem bạn được phép thực hiện thao tác này không.';
$l['error_nopermission_user_4'] = 'Tài khoản của bạn có thể  vẫn còn đang chờ được kích hoạt hoặc kiểm duyệt.';
$l['error_nopermission_user_5'] = 'Bạn đã truy cập trực tiếp trang này thay vì sử dụng các hình thức thích hợp hoặc liên kết.';
$l['error_nopermission_user_resendactivation'] = 'Gửi lại mã kích hoạt';
$l['error_nopermission_user_username'] = 'Bạn hiện đang đăng nhập với tên người dùng: \'{1}\'';
$l['logged_in_user'] = 'Trong tài khoản đăng nhập';
$l['error_too_many_images'] = 'Quá nhiều hình ảnh.';
$l['error_too_many_images2'] = 'Chúng tôi rất xin lỗi, nhưng chúng tôi không thể xử lý bài viết của bạn vì nó chứa quá nhiều hình ảnh. Hãy loại bỏ một số hình ảnh từ bài viết của bạn để tiếp tục.';
$l['error_too_many_images3'] = '<b>Lưu ý:</b> Số hình ảnh tối đa trong bài viết của bạn là';
$l['error_attach_file'] = 'Lỗi đính kèm tập tin';
$l['please_correct_errors'] = 'Xin vui lòng sửa các lỗi sau đây trước khi tiếp tục:';
$l['error_reachedattachquota'] = 'Xin lỗi, nhưng bạn không thể đính kèm tập tin này bởi vì bạn đã đạt đến hạn ngạch tập tin đính kèm của bạn {1}';
$l['error_maxattachpost'] = 'Xin lỗi, nhưng bạn không thể đính kèm tập tin này bởi vì bạn đã đạt đến số lượng tối đa cho phép file đính kèm trong bài viết của {1}';
$l['error_invaliduser'] = 'Người sử dụng chỉ định không hợp lệ hoặc không tồn tại.';
$l['error_invalidaction'] = 'Hành động không hợp lệ';
$l['error_messagelength'] = 'Xin lỗi, thông điệp của bạn quá dài và không thể được đăng. Hãy cố gắng rút ngắn tin nhắn của bạn và thử lại.';
$l['error_message_too_short'] = 'Xin lỗi, tin nhắn của bạn là quá ngắn và không thể được đăng.';
$l['failed_login_wait'] = 'Bạn đã đăng nhập sai quá số lần quy định. Bây giờ bạn phải chờ đợi {1} giờ {2} phút {3} giây trước khi bạn có thể đăng nhập lại.';
$l['failed_login_again'] = '<br />Bạn có <strong>{1}</strong> lần đăng nhập.';
$l['error_max_emails_day'] = 'Bạn không thể sử dụng \'Gửi chủ đề cho bạn bè "hay" Email của người sử dụng các tính năng bởi vì bạn đã sử dụng hết hạn ngạch được phân bổ của bạn gửi {1} tin nhắn trong vòng 24 giờ qua.';
$l['attachments_disabled'] = 'Bạn không thể sử dụng hệ thống tập tin đính kèm bởi vì nó đã bị vô hiệu hóa bởi người quản trị.';
$l['emailsubject_lostpw'] = 'Đặt lại mật khẩu tại {1}';
$l['emailsubject_passwordreset'] = 'Mật khẩu mới tại {1}';
$l['emailsubject_subscription'] = 'Trả lời mới tại {1}';
$l['emailsubject_randompassword'] = 'Mật khẩu của bạn cho {1}';
$l['emailsubject_activateaccount'] = 'Kích hoạt tài khoản tại {1}';
$l['emailsubject_forumsubscription'] = 'Có chủ đề mới trong {1}';
$l['emailsubject_reportpost'] = 'Có báo cáo bài viết tại {1}';
$l['emailsubject_reportprofile'] = 'Reported user at {1}';
$l['emailsubject_reportreputation'] = 'Reported reputation at {1}';
$l['emailsubject_reachedpmquota'] = 'Hộp thư đến của bạn đã đầy tại {1}';
$l['emailsubject_changeemail'] = 'Thay đổi Email tại {1}';
$l['emailsubject_newpm'] = 'Có tin nhắn mới tại {1} - {2}';
$l['emailsubject_newjoinrequest'] = 'Có yêu cầu gia nhập mới tại {1}';
$l['emailsubject_sendtofriend'] = 'Có một thảo luận thú vị tại {1}';
$l['emailsubject_changepassword'] = 'Thay đổi Password tại {1}';
$l['emailbit_viewthread'] = '... (truy cập các chủ đề để đọc thêm ..)';
$l['email_lostpw'] = '{1},

Để hoàn thành việc cài đặt lại mật khẩu tài khoản của bạn tại {2}, bạn cần phải bấm vào URL dưới đây để xác nhận.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Nếu liên kết trên không làm việc một cách chính xác, Hãy bấm vào liên kết sau

{3}/member.php?action=resetpassword

Bạn sẽ cần phải nhập thông tin sau:
Tên đăng nhập: {1}
Mã kích hoạt: {5}

Cảm ơn bạn,
{2} QTV';
$l['email_lostpw1'] = '{1},

Để hoàn thành việc cài đặt lại mật khẩu tài khoản của bạn tại {2}, bạn cần phải bấm vào URL dưới đây để xác nhận.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Nếu liên kết trên không làm việc một cách chính xác, Hãy bấm vào liên kết sau

{3}/member.php?action=resetpassword

Bạn sẽ cần phải nhập thông tin sau:
Địa chỉ email của bạn
Mã kích hoạt: {5}

Cảm ơn bạn,
{2} QTV';
$l['email_lostpw2'] = '{1},

Để hoàn thành việc cài đặt lại mật khẩu tài khoản của bạn tại {2}, bạn cần phải bấm vào URL dưới đây để xác nhận.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Nếu liên kết trên không làm việc một cách chính xác, Hãy bấm vào liên kết sau

{3}/member.php?action=resetpassword

You will need to enter the following:
Username: {1} (Or your email address)
Activation Code: {5}

Cảm ơn bạn,
{2} QTV';
$l['email_reportpost'] = '{1} từ {2} đã báo cáo bài viết này:

{3}
{4}/{5}

Lý do thành viên này báo cáo bài viết này:
{7}

Thông báo này đã được gửi đến tất cả các điều hành viên của diễn đàn này, hoặc tất cả các quản trị viên và người kiểm duyệt nếu không có người kiểm duyệt.

Vui lòng kiểm tra bài này càng sớm càng tốt.';
$l['email_reportprofile'] = '{1} from {2} has reported the following user:

{3}
{4}/{5}

The reason this user gave for reporting this user:
{6}

This message has been sent to all moderators of this forum, or all administrators and super moderators if there are no moderators.

Please check this user out as soon as possible.';
$l['email_reportreputation'] = '{1} from {2} has reported the following reputation:

{3}
{4}/{5}

The reason this user gave for reporting this reputation:
{6}

This message has been sent to all moderators of this forum, or all administrators and super moderators if there are no moderators.

Please check this reputation out as soon as possible.';
$l['email_passwordreset'] = '{1},

Mật khẩu của bạn tại {2} đã được thiết lập lại.

Mật khẩu mới của bạn là: {3}

Bạn sẽ cần mật khẩu này để đăng nhập vào các diễn đàn, sa khi bạn đăng nhập bạn nên thay đổi nó bằng cách vào Bảng điều khiển cá nhân của bạn.

Cảm ơn bạn,
{2} QTV';
$l['email_randompassword'] = '{1},

Cảm ơn bạn đã đăng ký trên {2}. Dưới đây là tên đăng nhập và mật khẩu được tạo ngẫu nhiên. Để đăng nhập vào {2}, bạn sẽ cần những chi tiết này.

Tên đăng nhập: {3}
Mật khẩu: {4}

Chúng tôi đề nghị bạn thay đổi mật khẩu của bạn ngay sau khi bạn đăng nhập. Bạn có thể làm điều này bằng cách vào User CP của bạn sau đó nhấp vào Thay đổi mật khẩu trên menu bên trái.

Cảm ơn bạn,
{2} QTV';
$l['email_randompassword1'] = '{1},

Cảm ơn bạn đã đăng ký trên {2}. Dưới đây là tên đăng nhập và mật khẩu được tạo ngẫu nhiên. Để đăng nhập vào {2}, bạn sẽ cần những chi tiết này.

Địa chỉ email
Mật khẩu: {4}

Chúng tôi đề nghị bạn thay đổi mật khẩu của bạn ngay sau khi bạn đăng nhập. Bạn có thể làm điều này bằng cách vào User CP của bạn sau đó nhấp vào Thay đổi mật khẩu trên menu bên trái.

Cảm ơn bạn,
{2} BQT';
$l['email_randompassword2'] = '{1},

Cảm ơn bạn đã đăng ký trên {2}. Dưới đây là tên người dùng và mật khẩu được tạo ngẫu nhiên. Để đăng nhập vào {2}, bạn sẽ cần những chi tiết này.

Tên đăng nhập: {3} (Hoặc địa chỉ email)
Mật khẩu: {4}

Chúng tôi đề nghị bạn thay đổi mật khẩu của bạn ngay sau khi bạn đăng nhập. Bạn có thể làm điều này bằng cách vào User CP của bạn sau đó nhấp vào Thay đổi mật khẩu trên menu bên trái.

Cảm ơn bạn,
{2} BQT';
$l['email_sendtofriend'] = 'Xin chào,

{1} từ {2} nghĩ bạn có thể quan tâm đến việc đọc các trang web sau đây:

{3}

{1} bao gồm thông báo sau:
------------------------------------------
{4}
------------------------------------------

Cảm ơn bạn,
{2} BQT
';
$l['email_forumsubscription'] = '{1},

{2} vừa mới gửi một chủ đề mới trong {3}. Đây là một diễn đàn bạn đã theo dõi tại {4}. 

Các chủ đề có tiêu đề {5} 

Dưới đây là một đoạn trích của chủ đề: 
- 
{6} 
- 

Để xem các chủ đề, bạn có thể vào đường dẫn sau: 
{7}/{8} 

Cũng có thể có chủ đề và trả lời mới khác, nhưng bạn sẽ không nhận được thông báo nữa cho đến khi bạn truy cập vào khu vực quản trị một lần nữa. 

Cảm ơn bạn, 
{4} BQT

------------------------------------------
Bỏ theo dõi:

Nếu bạn không muốn nhận được bất kỳ thông báo chi tiết nào của chủ đề mới trong diễn đàn này, hãy truy cập URL sau:
{7}/usercp.php?action=removesubscription&type=forum&fid={9}

------------------------------------------';
$l['email_activateaccount'] = '{1},

Để hoàn tất quá trình đăng ký trên {2}, bạn sẽ cần phải truy cập URL sau.

{3}/member.php?action=activate&uid={4}&code={5}

Nếu liên kết trên không làm việc một cách chính xác, hãy copy link sau dán vào trình duyệt của bạn

{3}/member.php?action=activate

Bạn cần phải nhập những thông tin sau:
Tên đăng nhập: {1}
Mã kích hoạt: {5}

Cảm ơn,
BQT {2}';
$l['email_activateaccount1'] = '{1},

Để hoàn tất quá trình đăng ký trên {2}, bạn sẽ cần phải truy cập URL sau.

{3}/member.php?action=activate&uid={4}&code={5}

Nếu liên kết trên không làm việc một cách chính xác, hãy copy link sau dán vào trình duyệt của bạn

{3}/member.php?action=activate

Bạn sẽ cần phải nhập vào sau đây:
Địa chỉ email của bạn
Mã kích hoạt: {5}

Cảm ơn,
{2} BQT';
$l['email_activateaccount2'] = '{1},

Để hoàn tất quá trình đăng ký trên {2}, bạn sẽ cần phải truy cập URL sau

{3}/member.php?action=activate&uid={4}&code={5}

Nếu liên kết trên không làm việc một cách chính xác, hãy copy link sau dán vào trình duyệt của bạn

{3}/member.php?action=activate

Bạn sẽ cần phải nhập vào sau đây:
Tên đăng nhập: {1} (Hoặc địa chỉ email của bạn)
Mã kích hoạt: {5}

Cảm ơn,
{2} BQT';
$l['email_subscription'] = '{1},

{2} vừa trả lời một chủ đề mà bạn đã theo dõi tại {3}. Chủ đề này được đặt tên là {4}. 

Dưới đây là một đoạn trích của thông điệp: 
------------------------------------------ 
{5} 
------------------------------------------ 

Để xem các chủ đề, bạn có thể vào đường dẫn sau: 
{6}/{7} 

Cũng có thể trả lời khác cho chủ đề này, nhưng bạn sẽ không nhận được thông báo nữa cho đến khi bạn truy cập vào trang quản trị một lần nữa. 

Cảm ơn bạn, 
{3} BQT

------------------------------------------ 
Hủy theo dõi: 

Nếu bạn không muốn tiếp tục nhận thông báo từ chủ đề này, bạn sẽ cần phải truy cập URL sau:
{6}/usercp.php?action=removesubscription&tid={8}

------------------------------------------';
$l['email_reachedpmquota'] = '{1},

Đây là một email tự động từ {2} để cho bạn biết rằng hộp thư tin nhắn riêng tư của bạn đã đạt đến giới hạn tối đa. 

Một hoặc nhiều người sử dụng có thể đã cố gắng để gửi cho bạn tin nhắn và đã không thành công khi làm như vậy vì điều này. 

Hãy xóa một số tin nhắn của bạn, bạn hiện đã được lưu trữ, ghi nhớ cũng bị xóa khỏi "Thùng rác".

Cảm ơn bạn,
{2} BQT
{3}';
$l['email_changeemail'] = '{1},

Chúng tôi đã nhận được yêu cầu {2} thay đổi địa chỉ email của bạn (xem chi tiết dưới đây).

Email cũ: {3}
Email mới: {4}

Nếu những thay đổi này là chính xác, xin vui lòng hoàn tất quá trình xác nhận trên {2} bằng cách truy cập vào URL sau.

{5}/member.php?action=activate&uid={8}&code={6}

Nếu liên kết trên không làm việc một cách chính xác, hãy copy link sau dán vào trình duyệt của bạn

{5}/member.php?action=activate

Bạn sẽ cần phải nhập vào:
Tên đăng nhập: {7}
Mã kích hoạt: {6}

Nếu bạn không xác nhận địa chỉ email mới của bạn hồ sơ của bạn sẽ không được cập nhật và vẫn sử dụng địa chỉ email hiện tại của bạn. 

Cảm ơn bạn,
{2} BQT
{5}';
$l['email_changeemail_noactivation'] = '{1},

Chúng tôi đã nhận được yêu cầu {2} thay đổi địa chỉ email của bạn (xem chi tiết dưới đây). 

Email cũ: {3} 
Email mớil: {4} 

Sự thay đổi này đã được tự động xử lý. Nếu bạn không yêu cầu thay đổi này, hãy liên lạc với quản trị viên. 

Cảm ơn bạn,
{2} BQT
{5}';
$l['email_changepassword'] = '{1},

Bạn nhận được email này vì bạn, hoặc một người nào đó có quyền truy cập vào tài khoản của bạn, gần đây đã thay đổi mật khẩu tài khoản của bạn. 

Tên đăng nhập: {1} 
Địa chỉ email: {2} 

Nếu bạn không yêu cầu thay đổi này, xin vui lòng liên lạc với quản trị viên. 

Cảm ơn bạn,
{3} BQT
{4}';
$l['email_newpm'] = '{1},

Bạn đã nhận được một tin nhắn mới {3} từ {2}: 

------------------------------------------
{5}
------------------------------------------

Để xem, trả lời hoặc chuyển tiếp tin nhắn này, bạn có thể làm theo liên kết này: 

{4}/private.php

Xin lưu ý rằng bạn sẽ không nhận được bất kỳ thông báo nào nữa về tin nhắn mới cho đến khi bạn ghé thăm {3}. 

Bạn có thể vô hiệu hóa các thông báo tin nhắn mới trên trang tùy chọn tài khoản của bạn:

{4}/usercp.php?action=options

Cảm ơn bạn,
{3} BQT
{4}';
$l['email_emailuser'] = '{1},

{2} từ {3} đã gửi cho bạn một thông báo sau:
------------------------------------------
{5}
------------------------------------------

Cảm ơn bạn,
{3} BQT
{4}

------------------------------------------
Không muốn nhận email từ các thành viên khác? 

Nếu bạn không muốn các thành viên khác có thể gửi email cho bạn vui lòng truy cập Bảng điều khiển của bạn và kích hoạt tùy chọn \'Ẩn email của bạn từ các thành viên khác\':
{4}/usercp.php?action=options

------------------------------------------';
$l['email_groupleader_joinrequest'] = '{1},

{2} đã yêu cầu tham gia {3} trong {4} (xem dưới đây).

Lý do: {5}

Để chấp nhận hoặc từ chối yêu cầu này, đi đến

{6}/managegroup.php?gid={7}

TCảm ơn bạn,
{3} BQT';
$l['email_contact_subject'] = 'Liên hệ: {1}';
$l['email_contact'] = 'E-mail: {1}
Thông tin diễn đàn: {2}
Địa chỉ IP: {3}
Tin nhắn:
{4}';
$l['pmsubject_subscription'] = 'Trả lời mới {1}';
$l['pm_subscription'] = '{1},

{2} vừa trả lời một chủ đề mà bạn đã đăng ký. Chủ đề này được đặt tên là {3}. 

Dưới đây là một đoạn trích của thông điệp: 
------------------------------------------ 
{4} 
------------------------------------------ 

Để xem các chủ đề, bạn có thể vào đường dẫn sau: 
[url] {5}/{6} [/url] 

Cũng có thể có trả lời khác cho chủ đề này, nhưng bạn sẽ không nhận được thông báo nào nữa cho đến khi bạn truy cập các chủ đề một lần nữa. 

------------------------------------------ 
Hủy theo dõi: 

Nếu bạn không muốn tiếp tục theo dõi chủ đề này, hãy truy cập URL sau:
[url]{5}/usercp.php?action=removesubscription&tid={7}[/url]


------------------------------------------';
$l['email_broken_task_subject'] = 'MyBB task error on {1}';
$l['email_broken_task'] = 'Your copy of MyBB running on {1} ({2}) has experienced an error with the task system.

The task file for {3} is missing.

This task has been disabled until issue is resolved.';
$l['error_attach_filename_length'] = 'Tên tệp \'{1}\' vượt quá độ dài tên tệp tối đa {2}. Vui lòng tải lên một tệp có tên tệp ngắn hơn.';
$l['email_report_comment_extra'] = '{1}: {2}';
