<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:02:48 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Tài liệu trợ giúp';
$l['nav_smilies'] = 'Danh sách mặt cười';
$l['nav_syndication'] = 'Chủ đề mới nhất Syndication (RSS)';
$l['aol_im'] = 'AOL IM';
$l['skype'] = 'Skype';
$l['yahoo_im'] = 'Yahoo IM';
$l['skype_center'] = 'Trung tâm Skype';
$l['chat_on_skype'] = 'Chat với {1} trên Skype';
$l['call_on_skype'] = 'Gọi {1} trên Skype';
$l['yahoo_center'] = 'Trung tâm Yahoo!';
$l['send_y_message'] = 'Gửi cho {1} một tin nhắn Yahoo!';
$l['view_y_profile'] = 'Xem hồ sơ Yahoo của {1}\'s .';
$l['aim_center'] = 'Trung tâm AOL IM';
$l['download_aim'] = 'Tải AIM';
$l['aim_remote'] = 'AIM từ xa';
$l['send_me_instant'] = 'Gửi tin nhắn';
$l['add_me_buddy_list'] = 'Thêm tôi vào danh sách bạn bè của bạn';
$l['add_remote_to_page'] = 'Thêm từ xa để trang của bạn';
$l['download_aol_im'] = 'Tải AOL Messenger';
$l['buddy_list'] = 'Danh sách bạn bề';
$l['online'] = 'Online';
$l['online_none'] = '<em>Bạn không có bạn bè trực tuyến</em>';
$l['offline'] = 'Offline';
$l['offline_none'] = '<em>Bạn không có bạn bè Offline</em>';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'Gửi tin nhắn riêng';
$l['last_active'] = '<strong>Hoạt động cuối:</strong> {1}';
$l['close'] = 'Đóng';
$l['no_buddies'] = '<em>Danh sách bạn bè của bạn hiện đang trống. Sử dụng UserCP hoặc truy cập hồ sơ người dùng thêm người dùng vào danh sách bạn bè của bạn.</em>';
$l['help_docs'] = 'Tài liệu trợ giúp';
$l['search_help_documents'] = 'Tìm kiếm tài liệu trợ giúp';
$l['search_by_name'] = 'Tìm theo tên';
$l['search_by_document'] = 'Tìm theo tài liệu';
$l['enter_keywords'] = 'Nhập từ khóa';
$l['search'] = 'Tìm kiếm';
$l['redirect_searchresults'] = 'Cảm ơn bạn, tìm kiếm của bạn đã được đệ trình và bây giờ bạn sẽ được chuyển tới danh sách kết quả.';
$l['search_results'] = 'Kết quả tìm kiếm';
$l['help_doc_results'] = 'Kết quả tìm kiếm';
$l['document'] = 'Tài liệu';
$l['error_nosearchresults'] = 'Xin lỗi, nhưng không có kết quả nào phù hợp với thông tin mà bạn cung cấp. Hãy thử lại với từ khóa khác.';
$l['no_help_results'] = 'Xin lỗi, nhưng không có kết quả nào phù hợp với thông tin mà bạn cung cấp.';
$l['error_helpsearchdisabled'] = 'Khả năng tìm kiếm các tài liệu trợ giúp đã bị vô hiệu hóa bởi Administrator.';
$l['smilies_listing'] = 'Danh sách mặt cười';
$l['name'] = 'Tên';
$l['abbreviation'] = 'Tên viết tắt';
$l['click_to_add'] = 'Bấm vào mặt cười để chèn chúng vào bài viết';
$l['close_window'] = 'Đóng cửa sổ';
$l['who_posted'] = 'Ai đã đăng?';
$l['total_posts'] = 'Tổng số bài viết:';
$l['user'] = 'Người dùng';
$l['num_posts'] = '# bài viết';
$l['forum_rules'] = '{1} - Quy định';
$l['error_invalid_limit'] = 'Các giới hạn mục cấp dữ liệu bạn đã nhập không hợp lệ. Hãy xác định một giới hạn hợp lệ.';
$l['syndication'] = 'RSS';
$l['syndication_generated_url'] = 'Liên kết RSS của bạn:';
$l['syndication_note'] = 'Dưới đây bạn có thể tạo ra các liên kết đến nguồn cấp dữ liệu RSS. Liên kết có thể được tạo ra cho tất cả các diễn đàn, mỗi diễn đàn, hoặc cho một số diễn đàn. Sau đó bạn sẽ được trình bày với một liên kết mà bạn có thể sao chép vào một trình đọc RSS. <i><a href="http://en.wikipedia.org/wiki/RSS" target="_blank">RSS là gì?</a></i>';
$l['syndication_forum'] = 'RSS diễn đàn:';
$l['syndication_forum_desc'] = 'Vui lòng chọn một diễn đàn từ bên phải. Sử dụng phím CTRL để chọn nhiều diễn đàn.';
$l['syndication_version'] = 'Phiên bản Feed:';
$l['syndication_version_desc'] = 'Vui lòng chọn các phiên bản của các nguồn cấp dữ liệu mà bạn muốn tạo.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (Default)';
$l['syndication_generate'] = 'Tạo liên kết RSS';
$l['syndication_limit'] = 'Giói hạn:';
$l['syndication_limit_desc'] = 'Số chủ đề để tải về cùng một lúc. Không nên vượt quá 50.';
$l['syndication_threads_time'] = 'chủ đề tại một thời gian';
$l['syndicate_all_forums'] = 'Syndicate các Diễn Đàn';
$l['redirect_markforumread'] = 'Chuyên mục được chọn đã được đánh dấu là đã đọc.';
$l['redirect_markforumsread'] = 'Tất cả các chuyên mục đã được đánh dấu là đã đọc.';
$l['redirect_forumpasscleared'] = 'Các mật khẩu được lưu trữ cho diễn đàn này đã bị xóa.';
$l['redirect_cookiescleared'] = 'Toàn bộ cookies đã được xóa.';
$l['error_invalidforum'] = 'Invalid forum';
$l['error_invalidhelpdoc'] = 'Các tài liệu trợ giúp được chỉ định không tồn tại.';
$l['error_invalidimtype'] = 'Thành viên này không có loại tài khoản này chỉ định tin nhắn tức thời trong hồ sơ của họ.';
$l['error_invalidsearch'] = 'An invalid search was specified.  Please go back and try again.';
$l['error_no_search_support'] = 'This database engine does not support searching.';
$l['error_searchflooding'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another {2} seconds before attempting to search again.';
$l['error_searchflooding_1'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another 1 second before attempting to search again.';
$l['dst_settings_updated'] = 'Chế độ tiết kiệm ánh sáng đã được điều chỉnh tự động.<br /><br />Bây giờ bạn sẽ được chuyển tới trang chủ.';
$l['no_smilies'] = 'Hiện tại không có mặt cười có sẵn.';
$l['syndication_version_json1'] = 'Nguồn cấp dữ liệu JSON 1';
