<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:05:43 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'Tin nhắn cá nhân';
$l['nav_send'] = 'Viết tin';
$l['nav_tracking'] = 'Theo dõi tin nhắn';
$l['nav_folders'] = 'Quản lý thư mục';
$l['nav_empty'] = 'Thư mục rỗng';
$l['nav_export'] = 'Xuất tin nhắn';
$l['nav_search'] = 'Tìm kiếm';
$l['nav_results'] = 'Kết quả';
$l['new_pm'] = 'Tin nhắn mới';
$l['old_pm'] = 'Tin nhắn cũ';
$l['reply_pm'] = 'Trả lời cho';
$l['fwd_pm'] = 'Chuyển tiếp tin nhắn';
$l['pms_disabled'] = 'Bạn không thể sử dụng chức năng tin nhắn cá nhân vì nó đã bị khoá bởi Administrator.';
$l['private_messaging'] = 'Tin nhắn cá nhân';
$l['inbox'] = 'Hộp thư đến';
$l['compose_message2'] = 'Soạn tin nhắn';
$l['manage_folders'] = 'Quản lý thư mục';
$l['pm_search_results'] = 'Kết quả tìm kiếm tin nhắn cá nhân';
$l['message_title'] = 'Tiêu đề tin nhắn';
$l['sender'] = 'Người gửi';
$l['sentto'] = 'Gửi tới';
$l['date_sent'] = 'Ngày/Thời gian gửi';
$l['desc'] = 'Giảm dần';
$l['asc'] = 'Tăng dần';
$l['delete_pm'] = 'Xóa';
$l['move_to'] = 'Di chuyển tới';
$l['or'] = 'hoặc';
$l['selected_messages'] = 'Chọn tin nhắn';
$l['go'] = 'Go!';
$l['pmspaceused'] = 'của ung lượng tin nhắn sử dụng.';
$l['jump_folder'] = 'Chuyển tới thư mục:';
$l['archive_messages'] = 'Xuất tin nhắn cá nhân';
$l['archive_note'] = 'Các công cụ sau đây sẽ cho phép bạn tải về hàng loạt tin nhắn của bạn để xem sau.';
$l['folders'] = 'Thư mục:';
$l['all_folders'] = 'Tất cả thư mục';
$l['date_limit'] = 'Giới hạn ngày:';
$l['date_limit_older'] = 'Xuất tin nhắn cũ hơn';
$l['date_limit_newer'] = 'Xuất tin nhắn mới hơn';
$l['date_limit_disregard'] = 'Bỏ qua ngày';
$l['date_limit_days'] = 'ngày';
$l['export_unread'] = 'Xuất tin nhắn chưa đọc?';
$l['delete_archived'] = 'Xóa tin nhắn đã xuất?';
$l['delete_archived_note'] = 'Bạn có muốn xóa các tin nhắn trong thư mục của bạn sau khi chúng được xuất ra?';
$l['export_format'] = 'Đinh dạng tập tin xuất ra:';
$l['export_format_note'] = 'Vui lòng chọn các loại tập tin để tải file đính kèm.';
$l['export_html'] = 'HTML(.html)';
$l['export_txt'] = 'Text(.txt)';
$l['export_csv'] = 'Excel (.csv)';
$l['private_messages_for'] = 'Tin nhắ riêng của {1}';
$l['exported_date'] = 'Đã xuất: {1}, {2}';
$l['subject'] = 'Tiêu đề:';
$l['to'] = 'Tới:';
$l['from'] = 'Từ:';
$l['sent'] = 'Gửi:';
$l['export_messages2'] = 'Tải tin nhắn';
$l['empty_folders'] = 'Làm trông thư mục tin nhắn cá nhân';
$l['empty_folders2'] = 'Thư mục trống';
$l['empty_note'] = 'Ở đây bạn có thể xóa tin nhắn. Bận chỉ cần chọ tin nhắn và bấm Xóa. Tin nhắn đã xóa không thể khôi phục lai.</strong>';
$l['num_messages'] = 'Bộ đếm tin nhắn';
$l['empty_q'] = 'Thư mục trống?';
$l['keep_unread'] = 'Giữ lại tin nhắn chưa đọc';
$l['pm_folders'] = 'Thư mục tin nhắn cá nhân';
$l['existing_folders'] = 'Thư mục hiện tại';
$l['edit_folder_note'] = 'Bạn có thể thay đổi tên của thư mục tin nhắn riêng hiện tại của bạn ở đây. Để xóa một thư mục, hãy xóa tên của thư mục. Một số thư mục không thể xóa <br /> <strong> Lưu ý:. Xóa một thư mục cũng sẽ xóa hết tin nhắn trong đó.</strong>';
$l['new_folders'] = 'Thêm thư mục mới';
$l['add_folders_note'] = 'Ở đây bạn có thể tạo các thư mục thông báo bổ sung. Bạn không cần phải điền vào tất cả các hộp văn bản.';
$l['update_folders'] = 'Cập nhật thư mục';
$l['cannot_be_removed'] = 'Không thể xóa';
$l['reached_warning'] = 'Cảnh báo. Số lượng tin nhắn của bạn đã đạt đến giới hạn cho phép.';
$l['reached_warning2'] = 'Để có thể nhận tin nhắn mới, bạn cần phải xóa những tin nhắn cũ.';
$l['deny_receipt'] = '[Từ chối nhận]';
$l['viewing_pm'] = 'Xem PM:';
$l['reply'] = 'Trả lời';
$l['reply_to_all'] = 'Trả lời tới tất cả';
$l['forward'] = 'Chuyển tiếp';
$l['compose_pm'] = 'Soạn tin nhẳn riêng';
$l['compose_to'] = 'Người nhận:';
$l['compose_bcc'] = 'BCC:';
$l['compose_bcc_show'] = 'BCC';
$l['compose_bcc_show_title'] = 'BCC là chức năng hỗ trợ người mù.';
$l['separate_names'] = 'Phân tách tên người dùng với một dấu phẩy.';
$l['max_recipients'] = '<br />Bạn có thể gửi tin nhắn này đến tối đa là <strong>{1}</strong> người.';
$l['compose_subject'] = 'Tiều đề:';
$l['compose_message'] = 'Tin nhắn:';
$l['compose_options'] = 'Tùy chọn:';
$l['message_icon'] = 'Biểu tượng tin nhắ:';
$l['options_sig'] = '<strong>Chữ ký:</strong> Chèn chữ ký vào tin nhắn.';
$l['options_disable_smilies'] = '<strong>Tắt mặt cười:</strong> Không cho phép mặt cười trong tin nhắn.';
$l['options_save_copy'] = '<strong>Lưu một bản sao:</strong> Lưu một bản sao của tin nhắn trong hộp thư đi.';
$l['options_read_receipt'] = '<strong>Phản hồi:</strong> Nhận một tin nhắn thông báo khi tin này được đọc.';
$l['send_message'] = 'Gửi tin nhắn';
$l['save_draft'] = 'Lưu thang bản nháp';
$l['preview'] = 'Xem trước';
$l['select_buddy'] = 'Hoặc chọn một người bạn:';
$l['pm_tracking'] = 'Theo dõi tin nhắn cá nhân';
$l['read_messages'] = 'Đọc rin nhắn';
$l['unread_messages'] = 'Tin nhắn chưa đọc';
$l['q'] = '?';
$l['dateread'] = 'Ngày đọc';
$l['stop_tracking'] = 'Dừng theo dõi';
$l['datesent'] = 'Ngày gửi';
$l['cancel'] = 'Hủy';
$l['export_date_sent'] = 'Ngày';
$l['export_folder'] = 'Thư mục';
$l['export_subject'] = 'Tiêu đề';
$l['export_to'] = 'Tới';
$l['export_from'] = 'Từ';
$l['export_message'] = 'Tin nhắn';
$l['not_sent'] = 'N/A (Không gửi)';
$l['at'] = 'tại';
$l['nomessages'] = 'Không có tin nhắn nào trong thư mục.';
$l['details'] = 'Chi tiết';
$l['message'] = 'Tin nhắn';
$l['buddy_list'] = 'Danh sách bạn bè';
$l['multiple_recipients'] = '<em>Nhiều người nhận</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Trả lời tin nhắn này.';
$l['forward_title'] = 'Chuyển tiếp tin nhắn này đến người dùng khác.';
$l['delete_title'] = 'Xóa tin nhắn';
$l['you_replied_on'] = 'Bạn trả lời tin nhắn này trên{1}';
$l['you_forwarded_on'] = 'Bạn chuyển tiếp tin nhắn này trên {1}';
$l['you_replied'] = 'Bạn trả lời tin nhắn này {1}';
$l['you_forwarded'] = 'Bạn chuyển tiếp tin nhắn này {1}';
$l['select_from_buddies'] = 'Chọn từ danh sách bạn bè.';
$l['no_readmessages'] = 'Hiện tại bạn không theo dõi bất kỳ tin nhắn đã đọc nào.';
$l['no_unreadmessages'] = 'Hiện tại bạn không có bất kỳ tin nhắn chưa đọc nào được theo dõi.';
$l['stop_tracking_all'] = 'Dừng theo dõi tất cả tin nhắn';
$l['enter_keywords'] = 'Nhập từ khóa';
$l['advanced_search'] = 'Tìm kiếm nâng cao';
$l['search_pms'] = 'SeTìm kiếm PMs';
$l['advanced_private_message_search'] = 'Tìm kiếm nâng cao tin nhắn cá nhân';
$l['search_criteria'] = 'Tiêu chuẩn tìm';
$l['keywords'] = 'Từ khóa';
$l['search_in_subject'] = 'Tìm trong tiêu đề';
$l['search_in_message'] = 'Tìm trong tin nhắn';
$l['message_status'] = 'Trạng thái tin nhắn';
$l['message_status_new'] = 'Mới';
$l['message_status_replied_to'] = 'Đã trả lời tới';
$l['message_status_forwarded'] = 'Đã chuyển tiếp';
$l['message_status_read'] = 'Đoc';
$l['folder'] = 'Thư mục';
$l['search_options'] = 'Tùy chọn tìm kiếm';
$l['sort_by'] = 'Sắp xếp theo';
$l['sort_by_subject'] = 'Sắp xếp theo: tiêu đề';
$l['sort_by_sender'] = 'Sắp xếp theo: người gửi';
$l['sort_by_date'] = 'Sắp xếp theo: ngày';
$l['ascending_order'] = 'Tăng dần';
$l['descending_order'] = 'Giảm dần';
$l['search_private_messages'] = 'Tìm kiếm tin nhắn cá nhân';
$l['check_all'] = 'Chọn toàn bộ';
$l['error_nopmsarchive'] = 'Xin lỗi, nhưng không có thông tin phù hợp với các tiêu chí mà bạn chỉ định.';
$l['error_invalidpmfoldername'] = 'Xin lỗi, nhưng tên thư mục mà bạn đã nhập có chứa các ký tự không được phép.';
$l['error_emptypmfoldername'] = 'Xin lỗi, nhưng một tên thư mục mà bạn đã nhập vào không chứa bất kỳ văn bản nào. Vui lòng nhập tên cho thư mục, hoặc để trống tên để xóa các thư mục.';
$l['error_invalidpmrecipient'] = 'Người nhận bạn đã nhập không hợp lệ hoặc không tồn tại, vui lòng quay trở lại và nhập vào tên người nhận.';
$l['error_invalidpm'] = 'PM không hợp lệ';
$l['error_pmrecipientreachedquota'] = 'Bạn không thể gửi một tin nhắn đến {1} bởi vì hộp thư đễn của anh/cô ấy đã đầy. Họ không thể nhận bất kỳ tin nhắn cho đến khi họ xóa hộ thư đến của họ. Một email đã được gửi đến họ về điều này, hãy thử gửi tin nhắn của bạn vào lúc khác.';
$l['error_recipientpmturnedoff'] = '{1} đã chọn không nhận các thông tin hoặc có thể bạn không được phép gửi tin nhắn, bạn có thể không gửi tin nhắn cá nhân cho người dùng này.';
$l['error_pmsturnedoff'] = 'Bạn hiện đang có những tin nhắn vô hiệu hóa trong hồ sơ của bạn. <br /> Để có thể sử dụng các hệ thống tin nhắn riêng thiết lập này phải được cho phép.';
$l['error_recipientignoring'] = 'Chúng tôi rất xin lỗi, nhưng chúng tôi không thể xử lý tin nhắn riêng của bạn đến {1}. Bạn không có quyền thực hiện hành động này.';
$l['error_pm_already_submitted'] = 'Bạn đã gửi những tin nhắn tương tự đến cùng một người nhận trong vòng 5 phút vừa qua.';
$l['error_nopms'] = 'Bạn phải có một hoặc nhiều tin nhắn cá nhân để truy cập chức năng này.';
$l['error_minsearchlength'] = 'Một hoặc nhiều thuật ngữ tìm kiếm của bạn ngắn hơn độ dài tối thiểu. Chiều dài từ khóa tìm kiếm tối thiểu là {1} ký tự. <br /> <br /> Nếu bạn đang cố gắng để tìm kiếm toàn bộ một cụm từ, hãy đặt nó trong dấu ngoặc kép. Ví dụ "sanvu88 - http://vansan.name.vn".';
$l['error_nosearchresults'] = 'Xin lỗi, nhưng không có kết quả được trả về bằng truy vấn thông tin mà bạn cung cấp. Hãy định nghĩa lại từ tìm kiếm và thử lại.';
$l['error_no_search_support'] = 'Cơ sở dữ liệu này không hỗ trợ tìm kiếm.';
$l['error_nosearchterms'] = 'Bạn đã không nhập bất kỳ điều kiện tìm kiếm tối thiểu nào, bạn phải nhập một số thuật ngữ tìm kiếm hoặc tên người dùng để tìm kiếm.';
$l['error_searchflooding_1'] = 'Xin lỗi, nhưng bạn chỉ có thể thực hiện mỗi tìm kiếm cách nhau {1} giây, vui lòng chờ thêm 1 giây trước khi cố gắng tìm kiếm một lần nữa.';
$l['error_searchflooding'] = 'Xin lỗi, nhưng bạn chỉ có thể thực hiện mỗi tìm kiếm cách nhau {1} giây. vui lòng chờ thêm {2} giây trước khi cố gắng tìm kiếm một lần nữa.';
$l['error_invalidsearch'] = 'Tìm kiếm không hợp lệ. Xin vui lòng thử lại.';
$l['redirect_pmsaved'] = 'Các tin nhắn đã được lưu trong thư mục Nháp của bạn.';
$l['redirect_pmstrackingstopped'] = 'Tính năng theo dõi tin nhắn đã được dừng lại.';
$l['redirect_pmstrackingcanceled'] = 'Tính năng theo dõi của tất cả các tin nhắn chưa đọc đã được dừng lại.';
$l['redirect_allpmstrackingstopped'] = 'Tính năng theo dõi của tất cả các tin nhắn đã đọc đã được dừng lại.';
$l['redirect_pmsmoved'] = 'Các tin nhắn được lựa chọn đã được di chuyển.';
$l['redirect_pmsdeleted'] = 'Các tin nhắn được lựa chọn đã bị xóa.';
$l['redirect_pmsent'] = 'Cảm ơn bạn, thông tin của bạn đã được gửi. <br /> Bây giờ bạn sẽ đưa trở về hộp thư tin nhắn cá nhân.';
$l['redirect_pmfoldersupdated'] = 'Cảm ơn bạn, thư mục tin nhắn cá nhân của bạn đã được cập nhật.<br />Bây giờ bạn sẽ được đưa trở về Hộp thư đến của bạn.';
$l['redirect_pmfoldersemptied'] = 'Các thư mục tin nhắn riêng đã được làm trống <br /> Bây giờ bạn sẽ được đưa trở về Hộp thư đến của bạn.';
$l['redirect_searchresults'] = 'Cảm ơn bạn, tìm kiếm của bạn đã được đệ trình và bây giờ bạn sẽ được đưa vào danh sách kết quả.';
$l['quick_reply'] = 'Trả lời nhanh';
$l['message_note'] = 'Nhập trả lời của bạn vào đây.';
$l['send_reply'] = 'Gửi trả lời';
$l['quickreply_signature'] = 'Chữ ký';
$l['quickreply_disable_smilies'] = 'Tắt mặt cười';
$l['quickreply_save_copy'] = 'Lưu bản sao';
$l['quickreply_read_receipt'] = '<strong>Yêu cầu đọc đã tiếp nhận</strong>';
$l['error_invalidmovefid'] = 'Thư mục bạn đang cố gắng chuyển tin nhắn của mình không hợp lệ. Hãy quay trở lại và thử lại.';
