<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:06:00 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Cảm ơn bạn, chủ đề đã được đánh giá thành công. Bây giờ bạn sẽ được trở lại chủ đề.';
$l['error_invalidrating'] = 'Bạn đã lựa chọn đánh giá không hợp lệ cho chủ đề này. Hãy quay trở lại và thử lại.';
$l['error_alreadyratedthread'] = 'Xin lỗi, nhưng bạn đã đánh giá chủ đề này.';
$l['error_cannotrateownthread'] = 'Xin lỗi, bạn không thể đánh giá chủ đề của chính bạn.';
$l['rating_votes_average'] = '{1} Vote(s) - {2} vượt quá 5 sao';
$l['one_star'] = '1 sao vượt quá 5';
$l['two_stars'] = '2 sao vượt quá 5';
$l['three_stars'] = '3 sao vượt quá 5';
$l['four_stars'] = '4 sao vượt quá 5';
$l['five_stars'] = '5 sao vượt quá 5';
$l['rating_added'] = 'Đánh giá của bạn đã được thêm!';
$l['thread_doesnt_exist'] = 'Bạn không thể đánh giá một chủ đề không tồn tại.';
