<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:06:30 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Lý do báo cáo:';
$l['report_to_mod'] = 'Báo cáo nội dung tới moderator';
$l['close_window'] = 'Đóng cửa sổ';
$l['report_content'] = 'Báo cáo nội dung';
$l['report_reason_post'] = 'Báo cáo bài viết';
$l['report_reason_profile'] = 'Báo cáo hồ sơ';
$l['report_reason_reputation'] = 'Báo cáo danh tiếng';
$l['report_reason_bad'] = 'Inappropriate Content';
$l['report_reason_spam'] = 'Nội dung Spam';
$l['report_reason_rules'] = 'Vi phạm nội quy của diễn đàn';
$l['report_reason_wrong'] = 'Đăng sai diễn đàn';
$l['report_reason_other'] = 'Khác';
$l['success_report_voted'] = 'Cảm ơn báo cáo nội dung này. <br /> BQT sẽ kiểm tra báo cáo của bạn trong thời gian sớm nhất có thể.';
$l['error_report_length'] = 'Vui lòng cung cấp một lý do chi tiết cho báo cáo của bạn.';
$l['error_invalid_report'] = 'Nội dung {1} này không tồn tại hoặc là được phép báo cáo.';
$l['error_report_duplicate'] = 'Nội dung này đã được báo cáo bởi các thành viên khác.<br />Bạn cũng có thể báo cáo nội dung này dưới đây.';
$l['report_reason_other_description'] = 'Nếu bạn chọn lý do Khác, vui lòng cung cấp một lý do để báo cáo nội dung này.';
$l['error_invalid_report_reason'] = 'Lý do được chọn không hợp lệ.';
$l['error_comment_required'] = 'Một bình luận bổ sung là cần thiết cho lý do đã chọn.';
