<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt
// Author of the language pack : Translate by VietMyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1810
// Last edited in MyBB Editor by : tamtangphap
// Last edited date : Sun, 19 Jul 2020 14:09:33 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Xóa bình chọn';
$l['close_thread'] = 'Đóng chủ đề';
$l['stick_thread'] = 'Đính chủ đề';
$l['author'] = 'Tác giả';
$l['message'] = 'Tin nhắn';
$l['threaded'] = 'Chế độ Threaded';
$l['linear'] = 'Chế độ Linear';
$l['thread_modes'] = 'Chế độ chủ đề';
$l['next_oldest'] = 'Bài trước';
$l['next_newest'] = 'Bài tiếp theo';
$l['view_printable'] = 'Xem ở phiên bản có thể in';
$l['send_thread'] = 'Gửi chủ đề cho bạn bè';
$l['subscribe_thread'] = 'Theo dõi chủ đề này';
$l['unsubscribe_thread'] = 'Bỏ theo dõi chủ đề này';
$l['add_poll_to_thread'] = 'Thêm bình chọn cho chủ đề này';
$l['moderation_options'] = 'Công cụ quản lý:';
$l['delayed_moderation'] = 'Kiểm duyệt bị trì hoãn';
$l['thread_notes'] = 'Sửa / Xem ghi chú chủ đề';
$l['open_close_thread'] = 'Mở / Đóng chú đề';
$l['approve_thread'] = 'Phê duyệt';
$l['unapprove_thread'] = 'Bỏ phê duyệt';
$l['soft_delete_thread'] = 'Xóa mềm';
$l['restore_thread'] = 'Khôi phục chủ đề';
$l['delete_thread'] = 'Xóa vĩnh viễn';
$l['delete_posts'] = 'Xóa bài viết có chọn lọc';
$l['move_thread'] = 'Di chuyển / Sao chép';
$l['stick_unstick_thread'] = 'Đính / Bỏ đính';
$l['split_thread'] = 'Tách chủ đề';
$l['merge_threads'] = 'Trộn chủ đề';
$l['remove_redirects'] = 'Hủy bỏ chuyển hướng';
$l['remove_subscriptions'] = 'Xóa toàn bộ theo dõi';
$l['poll'] = 'Bình chọn:';
$l['show_results'] = 'Hiện kết quả';
$l['edit_poll'] = 'Edit poll';
$l['public_note'] = '<b>Chú ý:</b> Đây là một cuộc thăm dò công khai, những người khác có thể nhìn thấy những gì bạn bình chọn.';
$l['total'] = 'Tổng';
$l['vote'] = 'Vote!';
$l['total_votes'] = '{1} vote(s)';
$l['you_voted'] = '* Bạn bình chọn cho mục này.';
$l['poll_closed'] = 'Bình chọn đã bị đóng.';
$l['poll_closes'] = 'Bình chọn sẽ đóng sau: {1}';
$l['already_voted'] = 'Bạn đã bình chọn trong cuộc bình chọn này.';
$l['undo_vote'] = 'Hủy vote';
$l['quick_reply'] = 'Trả lời nhanh';
$l['message_note'] = 'Nhập tin nhắn của bạn ở đây.';
$l['signature'] = 'Chữ ký';
$l['email_notify'] = 'Email thông báo';
$l['disable_smilies'] = 'Tắt Smilies';
$l['post_reply'] = 'Gửi trả lời';
$l['post_reply_img'] = 'Gửi trả lời';
$l['new_reply'] = 'Trả lời';
$l['search_button'] = 'Tìm kiếm';
$l['post_thread'] = 'Đăng chủ đề';
$l['preview_post'] = 'Xem trước';
$l['rating_average'] = '{1} Vote(s) - Trung bình {2}';
$l['rate_thread'] = 'Đánh giá chủ đề:';
$l['thread_rating'] = 'Đánh giá chủ đề:';
$l['similar_threads'] = 'Chủ đề liên quan...';
$l['thread'] = 'Chủ đề';
$l['replies'] = 'Trả lời';
$l['views'] = 'Xem';
$l['lastpost'] = 'Bài viết cuối';
$l['messages_in_thread'] = 'Tin nhắn trong chủ đề này';
$l['users_browsing_thread'] = 'Thành viên đang xem chủ đề:';
$l['users_browsing_thread_guests'] = '{1} Khách';
$l['users_browsing_thread_invis'] = '{1} thành viên ẩn';
$l['users_browsing_thread_reading'] = 'Đang đọc...';
$l['inline_soft_delete_posts'] = 'Xóa mềm';
$l['inline_restore_posts'] = 'Khôi phục bài viết';
$l['inline_delete_posts'] = 'Xóa vĩnh viễn';
$l['inline_merge_posts'] = 'Trộn bài viết';
$l['inline_split_posts'] = 'Tách bài viết';
$l['inline_move_posts'] = 'Di chuyển bài viết';
$l['inline_approve_posts'] = 'Phê duyệt';
$l['inline_unapprove_posts'] = 'Bỏ phê duyệt';
$l['inline_post_moderation'] = 'Inline Post Moderation:';
$l['inline_go'] = 'Go';
$l['clear'] = 'Xóa';
$l['thread_closed'] = 'Chủ đề đã đóng';
$l['no_subject'] = 'Không có tiêu đề';
$l['error_nonextnewest'] = 'Không có chủ đề mới hơn.';
$l['error_nonextoldest'] = 'Không có chủ đề cũ hơn.';
$l['quickreply_multiquote_selected'] = 'Bạn đã chọn một bài viết hoặc hơn nhiều hơn để trích dẫn.';
$l['quickreply_multiquote_now'] = 'Trích dẫn bài viết';
$l['or'] = 'hoặc';
$l['quickreply_multiquote_deselect'] = 'hủy lựa chọn';
$l['search_thread'] = 'Tìm kiếm chủ đề';
$l['enter_keywords'] = 'Nhập từ khóa';
$l['view_thread_notes'] = 'Ghi chú chủ đề';
$l['view_all_notes'] = 'Xem toàn bộ ghi chú';
$l['save_changes'] = 'Lưu thay đổi';
$l['cancel_edit'] = 'Hủy chỉnh sửa';
$l['quick_edit_update_error'] = 'Đã xảy ra lỗi khi chỉnh sửa câu trả lời của bạn:';
$l['quick_reply_post_error'] = 'Đã xảy ra lỗi khi đăng câu trả lời của bạn:';
$l['quick_delete_error'] = 'Đã xảy ra lỗi khi xóa câu trả lời của bạn:';
$l['quick_delete_success'] = 'Các bài viết đã được xóa thành công.';
$l['quick_delete_thread_success'] = 'Các chủ đề đã được xóa thành công.';
$l['quick_restore_error'] = 'Có lỗi khi phục hồi câu trả lời của bạn:';
$l['quick_restore_success'] = 'Các bài viết đã được khôi phục thành công.';
$l['no_voting_permission'] = 'Bạn không được phép bỏ phiếu trong cuộc thăm dò này.';
$l['post_deleted_error'] = 'Bạn không thể thực hiện hành động này đến một bài viết đã bị xóa.';
